apiVersion: v1
data:
#  config is in repository https://github.com/alphalab-hq/alc-accounts-status-server/blob/main/Alc.Accounts.StatusServer.WebApi/configs/appsettings.yaml
  config.yaml: |-
        
kind: ConfigMap
metadata:
  name: account-manager-config
