QuoteServers:
  - name: qs-korbit-201
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-korbit:2025.1.14.72-100f6ef
    requests:
      cpu: 1100m
      memory: 2000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      QuoteServer:
        ShardId: 200
        ExchangeName: Korbit
        Korbit:
          ExchangeConnection:
            WebsocketApi:
              Uri: "wss://ws2.korbit.co.kr/v1/user/push"
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 20

          Symbols:
            - Name: SAND/KRW
            - Name: DOT/KRW
            - Name: ETC/KRW
            - Name: ETH/KRW
            - Name: KLAY/KRW
            - Name: SOL/KRW
            - Name: XRP/KRW
            - Name: BCH/KRW
            - Name: BTC/KRW
            - Name: TRX/KRW
            - Name: EOS/KRW
            - Name: LINK/KRW
            - Name: FIL/KRW
            - Name: USDC/KRW
            - Name: ADA/KRW
            - Name: STX/KRW
            - Name: FLOW/KRW
            - Name: AVAX/KRW
            - Name: CTC/KRW
            - Name: WEMIX/KRW
            - Name: XPLA/KRW
            - Name: STRK/KRW
            - Name: WLD/KRW
            - Name: SHIB/KRW
            - Name: PEPE/KRW
            - Name: DOGE/KRW
            - Name: SEI/KRW
            - Name: SUI/KRW
            - Name: NEAR/KRW
            - Name: QTUM/KRW
            - Name: XLM/KRW
            - Name: BSV/KRW
            - Name: ARB/KRW
            - Name: ALGO/KRW
            - Name: BNB/KRW
            - Name: MED/KRW
            - Name: AXS/KRW
            - Name: GALA/KRW
            - Name: GRT/KRW
            - Name: ASTR/KRW
            - Name: PYTH/KRW
            - Name: ETHFI/KRW
            - Name: BONK/KRW
            - Name: W/KRW
            - Name: PCI/KRW
            - Name: ONDO/KRW
            - Name: PENDLE/KRW
            - Name: USDT/KRW
            - Name: VET/KRW
            - Name: MINA/KRW

        Pipeline:
          DepthBookMaintainer:
            LevelsCap: 50

          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-sel-01:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
