apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-exmo-201
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-exmo:2022.9.12.14-9f2423fef832aba4634ccf035b1aa10efde76d25
  replicas: 1
  destiny: dg-rt
  cpu_request: 1000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: Exmo

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 15
        Symbols:
          - Name: ADA/USD
          - Name: TRX/USD
          - Name: XRP/ETH
          - Name: ETC/BTC
          - Name: ADA/USDT
          - Name: BTC/USD
          - Name: ETH/USD
          - Name: XRP/USD
          - Name: BTC/USDT
          - Name: ETH/USDT
          - Name: ETH/BTC
          - Name: XRP/USDT
          - Name: ETC/USD
          - Name: NEO/USD
          - Name: XRP/BTC
          - Name: BCH/USD
          - Name: ETH/UAH
          - Name: ETH/LTC
          - Name: BTC/UAH
          - Name: BTC/EUR
          - Name: ADA/BTC
          - Name: ALGO/USDT
          - Name: LTC/USD
          - Name: ALGO/BTC
          - Name: BTC/GBP
          - Name: LTC/BTC
          - Name: ETH/EUR

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-fra-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
            Extension: InstanceId
