apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: false

      Workflow:
        Type: SplitBySymbolCount
        SymbolsCount: 300
        InitialWorkflowCount: 3
    
      ZmqTransport:
        DefaultEndpointName: "default"
        Endpoint:
          default:
            - ">tcp://dg-proxy.dg-sel-01:11900"
          
        LocalByteCacheSize: 65536
        ReceiveHighWatermark: 300000
        
      Extension: InstanceId
      Subscription: NonSubSampled
      ExtensionDeserializationErrorHandling: None

    Subscription:
      Prefix: ""
      ExporterName: "qs-exporter-seoul-csharp"
      Exchanges:
        default:
          - "Upbit"
          - "Korbit"
          - "Bithumb"
          - "Coinone"

    MetricConfigurationProvider:
      DefaultEnabled: true
      Rules:
        - Symbol: "XPLA/KRW"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "Bithumb"
          Enabled: true
        - Symbol: "PEAQ/KRW"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "Bithumb"
          Enabled: true
        - Metric: "al_qs_book_agg_amt_from_mid"
          Enabled: false
        - Metric: "al_qs_prc_for_usd_amt"
          Enabled: false

kind: ConfigMap
metadata:
  name: qs-exporter-config-csharp
