QuoteServers:
  - name: qs-coingecko-201
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-coingecko:2024.9.26.4-1a014d8
    requests:
      cpu: 1100m
      memory: 1000Mi
    limits:
      cpu: 4000m
      memory: 4000Mi
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt
        effect: NoSchedule
    prometheusPodScrape: true
    config: |
      SecurityMaster:
        RefreshIntervalInSeconds: 1800
        FileLoader:
          CurrencyFilePath: /etc/security_master/security_master.ccy.yaml.latest
          ExchangesFilePath: /etc/security_master/security_master.exch.yaml.latest
          LoadAllSecuritiesDataFiles: false
          SecuritiesDataFilesPath: /etc/security_master
        
      QuoteServer:
        ShardId: 0
        ExchangeName: CoinGecko
        Endpoint: "tcp://dg-proxy.dg-nva-01:11800"
        DevelopmentMode: false

      CoinGecko:
          Url: "https://api.coingecko.com/api/v3"
          SleepTime: 0.00:00:15.0
          Symbols:
            - USDB/USD
            - EZETH/USD
            - wrsETH/USD
            - DOGS/USD
            - LAVAN/USD
            - STONE/USD
            - WEETH/USD
            - TBILL/USD
            - XCUR/USD

      RateLimiter:
        Http:
          UsageLimit: 20
          Interval: 0.00:01:00.0
          MinAcquireGap: 0.00:00:05.0
          RequestCosts:
            Snapshot: 1
