apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-hundredx-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-hundredx:2024.6.26.258-1d51a9f
  replicas: 0
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    Serilog:
      MinimumLevel:
        Default: Debug
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: HundredxFut

      Monitor:
        MaxSymbolsPerConnection: 1
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: WBTC/USDB
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: WETH/USDB
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: WSOL/USDB
              NamePatterns:
                - '_Perpetual'

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"

          V3BinaryFormat:
            DevelopmentMode: false
