apiVersion: v1
data:
  config.yaml: |-
    Serilog:
      MinimumLevel:
        Default: Information
        Override:
          Microsoft: Warning
          System.Net.Http.HttpClient: Warning
      WriteTo:
        -   Name: Console
            Args:
              theme: "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console"
              outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Prefix}{Message:lj}{NewLine}{Exception}"
        -   Name: File
            Args:
              path:  "./logs/qscs-.txt"
              rollingInterval: Day
              outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Prefix}{Message:lj} {Properties:j}{NewLine}{Exception}"

    QsClient:
      DevelopmentMode: false

      Workflow:
        Type: SplitBySymbolCount
        SymbolsCount: 800
        InitialWorkflowCount: 5
    
      ZmqTransport:
        DefaultEndpointName: "default"
        Endpoint:
          default:
            - ">tcp://dg-proxy.dg-tokyo-02:11900"
            - ">tcp://dg-proxy.dg-tokyo-04:11900"
            - ">tcp://dg-proxy.dg-tokyo-09:11900"
         
        LocalByteCacheSize: 65536
        ReceiveHighWatermark: 300000
        
      Extension: InstanceId
      Subscription: NonSubSampled
      ExtensionDeserializationErrorHandling: None

    Subscription:
      Prefix: ""
      ExporterName: "qs-exporter-tokyo-csharp-2"
      Exchanges:
        default:
          - "BinanceFut"
          - "BitBank"
          - "KuCoinFut"
          - "BigONE"
          - "BluefinSuiFut"
          - "ParadexFut"
          - "GateIOFut"
          - "WooX"
          - "Hyperliquid"
          - "Bitget"
          - "SynQuoteFut"
          - "OKCoinJP"

        regional:

    MetricConfigurationProvider:
      DefaultEnabled: true
      Rules:
        - Symbol: "RARI/USDT"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "Bitget"
          Enabled: true
        - Symbol: "XPLA/USDT"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "Bitget"
          Enabled: true
        - Symbol: "PEAQ/USDT"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "Bitget"
          Enabled: true
        - Metric: "al_qs_book_agg_amt_from_mid"
          Enabled: false
        - Metric: "al_qs_prc_for_usd_amt"
          Enabled: false

kind: ConfigMap
metadata:
  name: qs-exporter-config-csharp-2
