apiVersion: v1
kind: Service
metadata:
  name: dg-proxy
  labels:
    app: dg-proxy
spec:
  type: ClusterIP
  selector:
    app: dg-proxy
  ports:
    - name: dg-in
      protocol: TCP
      port: 11800
      targetPort: 11800
    - name: dg-out
      protocol: TCP
      port: 11900
      targetPort: 11900