apiVersion: v1
data:
  config.yaml: |
    SecurityMaster:
      RefreshIntervalInSeconds: 540
      Exchanges:
        okcoinjp:
          FileLoader:
            ExchangeDataFile: /etc/security_master/security_master.okcoinjp.prop.yaml.latest
      FileLoader:
        DisableNotificationsService: true
        CurrencyFilePath: /etc/security_master/security_master.ccy.yaml.latest
        ExchangesFilePath: /etc/security_master/security_master.exch.yaml.latest

    QuoteServer:
      ShardId: 200
      ExchangeName: OKCoinJP
      Monitor:
        Symbols:
          - Name: BTC/JPY
          - Name: ADA/JPY
          - Name: APT/JPY
          - Name: ASTR/JPY
          - Name: BAT/JPY
          - Name: DAI/JPY
          - Name: DOGE/JPY
          - Name: ENJ/JPY
          - Name: FIL/JPY
          - Name: IOST/JPY
          - Name: LTC/JPY
          - Name: MATIC/JPY
          - Name: OAS/JPY
          - Name: OKB/JPY
          - Name: QTUM/JPY
          - Name: SHIB/JPY
          - Name: SUI/JPY
          - Name: TRX/JPY
          - Name: XRP/JPY
          - Name: ZIL/JPY
        DefaultConnectionCount: 1
      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    QsLite:
      HotPathBusyWait: false
      ColdPathBusyWait: false
      HotPathAffinityMask: ""
      ColdPathAffinityMask: ""
      MonitoringServerPort: 5001
      Exchanges:
        okcoinjp:
          WsEndpoint: "wss://connect.okcoin.jp:443/ws/v3"
          HttpEndpoint: "https://www.okcoin.jp"
          NumTickerSubscriptions: 5
          NumTradeSubscriptions: 5
          RateLimiter:
            Window: "00:00:01"
            AutoReplenishment: true
            PermitLimit: 20  # count
            QueueLimit: 20   # sum
    PerfCollector:
      HistogramDumpInterval: 24:00:00
kind: ConfigMap
metadata:
  name: qs-okcoinjp-201-config
