apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: false

      Workflow:
        Type: SplitBySymbolCount
        SymbolsCount: 400
        InitialWorkflowCount: 4
    
      ZmqTransport:
        Endpoint:
          default:
            - ">tcp://dg-proxy.dg-irl-01:11900"
         
        LocalByteCacheSize: 65536
        ReceiveHighWatermark: 300000
        
      Extension: InstanceId
      Subscription: NonSubSampled
      ExtensionDeserializationErrorHandling: None

    Subscription:
      Prefix: ""
      ExporterName: "qs-exporter-ireland-csharp"
      Exchanges:
        - "Deribit"
        - "Poloniex"   
        - "BtcTurk"
        - "DeribitOptions"
        - "DeribitSpot"
        - "DeribitMerged"

    MetricConfigurationProvider:
      DefaultEnabled: true
      Rules:
        - Exchange: "LFQS"
          Enabled: false
        - Symbol: "STETH/ETH"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "DeribitSpot"
          Enabled: true
        - Symbol: "STETH/USDC"
          Metric: "al_qs_book_agg_amt_from_mid"
          Exchange: "DeribitSpot"
          Enabled: true
        - Metric: "al_qs_book_agg_amt_from_mid"
          Enabled: false
        - Metric: "al_qs_prc_for_usd_amt"
          Enabled: false


          


kind: ConfigMap
metadata:
  name: qs-exporter-config-csharp
