apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-synquotefut-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-synquote:2024.9.20.332-26d8cae
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 3000Mi
  cpu_limit: 2000m
  memory_limit: 3000Mi
  config: |-
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    
    QuoteServer:
      ShardId: 200
      ExchangeName: SynQuoteFut
      SynQuoteFut:
        WsUrl: wss://prod-api.synquote.com/ws
        RestUrl: https://prod-api.synquote.com
      Monitor:
        MaxSymbolsPerConnection: 1
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: BTC/USDC
              NamePatterns:
                - _Perpetual
            - UnderlyingName: ETH/USDC
              NamePatterns:
                - _Perpetual
            - UnderlyingName: SOL/USDC
              NamePatterns:
                - _Perpetual

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"

          V3BinaryFormat:
            DevelopmentMode: false
