QuoteServers:
  - name: qs-kucoinfut-201
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 200
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 5
          DerivedSymbols:
            Type: Futures
            Symbols:
            - UnderlyingName: BTC/USDT
            - UnderlyingName: DOT/USD
            - UnderlyingName: ETH/USDC
            - UnderlyingName: FLOW/USDT
            - UnderlyingName: AMB/USDT
            - UnderlyingName: HOOK/USDT
            - UnderlyingName: MDT/USDT
            - UnderlyingName: ZEC/USDT
            - UnderlyingName: RIF/USDT
            - UnderlyingName: ARKM/USDT
            - UnderlyingName: NFP/USDT

        Pipeline:
          Disruptor:
            DisruptorStatsDecoratorEnabled: false
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        Enabled: false
  - name: qs-kucoinfut-202
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 201
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: ETH/USDT
              - UnderlyingName: APE/USDT
              - UnderlyingName: ZIL/USDT
              - UnderlyingName: SOL/USDT
              - UnderlyingName: KAVA/USDT
              - UnderlyingName: TRX/USDT
              - UnderlyingName: SUSHI/USDT
              - UnderlyingName: SSV/USDT
              - UnderlyingName: NEO/USDT
              - UnderlyingName: ONE/USDT
              - UnderlyingName: CHR/USDT
              - UnderlyingName: XLM/USDT
              - UnderlyingName: TURBO/USDT
              - UnderlyingName: XMR/USDT
              - UnderlyingName: THETA/USDT
        Pipeline:
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
  - name: qs-kucoinfut-203
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 202
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
            - UnderlyingName: CTSI/USDT
            - UnderlyingName: AXS/USDT
            - UnderlyingName: MANA/USDT
            - UnderlyingName: LINK/USDT
            - UnderlyingName: DOT/USDT
            - UnderlyingName: LINA/USDT
            - UnderlyingName: JASMY/USDT
            - UnderlyingName: BNB/USDT
            - UnderlyingName: MASK/USDT
            - UnderlyingName: ATOM/USDT
            - UnderlyingName: DYDX/USDT
            - UnderlyingName: SUI/USDT
            - UnderlyingName: LTC/USDT
            - UnderlyingName: COMP/USDT
            - UnderlyingName: FTT/USDT
            - UnderlyingName: KAS/USDT
            - UnderlyingName: BOB/USDT

        Pipeline:
          Disruptor:
            DisruptorStatsDecoratorEnabled: false
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        Enabled: false
  - name: qs-kucoinfut-204
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 203
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
            - UnderlyingName: APT/USDT
            - UnderlyingName: SAND/USDT
            - UnderlyingName: AVAX/USDT
            - UnderlyingName: WAVES/USDT
            - UnderlyingName: VRA/USDT
            - UnderlyingName: GRT/USDT
            - UnderlyingName: ARPA/USDT
            - UnderlyingName: GALA/USDT
            - UnderlyingName: LDO/USDT
            - UnderlyingName: HIGH/USDT
            - UnderlyingName: 10000LADYS/USDT
            - UnderlyingName: YFI/USDT
            - UnderlyingName: LPT/USDT
            - UnderlyingName: YGG/USDT
            - UnderlyingName: OGN/USDT
            - UnderlyingName: DUSK/USDT
            - UnderlyingName: C98/USDT
            - UnderlyingName: FLM/USDT

        Pipeline:
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
  - name: qs-kucoinfut-205
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 204
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
            - UnderlyingName: FIL/USDT
            - UnderlyingName: NEAR/USDT
            - UnderlyingName: BLUR/USDT
            - UnderlyingName: ALGO/USDT
            - UnderlyingName: WOO/USDT
            - UnderlyingName: ETC/USDT
            - UnderlyingName: EOS/USDT
            - UnderlyingName: QNT/USDT
            - UnderlyingName: NKN/USDT
            - UnderlyingName: ONEINCH/USDT
            - UnderlyingName: VET/USDT
            - UnderlyingName: CRV/USDT
            - UnderlyingName: RUNE/USDT
            - UnderlyingName: MINA/USDT
            - UnderlyingName: XVG/USDT
            - UnderlyingName: CVC/USDT
            - UnderlyingName: XRP/USD
            - UnderlyingName: SXP/USDT
            - UnderlyingName: UNI/USDT
            - UnderlyingName: ICP/USDT
            - UnderlyingName: IMX/USDT
            - UnderlyingName: STX/USDT
            - UnderlyingName: DASH/USDT
            - UnderlyingName: EGLD/USDT
            - UnderlyingName: BCH/USDT
            - UnderlyingName: XEC/USDT
            - UnderlyingName: ZRX/USDT
            - UnderlyingName: CYBER/USDT


        Pipeline:
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
  - name: qs-kucoinfut-206
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 205
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: GMT/USDT
              - UnderlyingName: XRP/USDT
              - UnderlyingName: ADA/USDT
              - UnderlyingName: BTC/USD
                NamePatterns:
                - _Perpetual
              - UnderlyingName: ARB/USDT
              - UnderlyingName: OP/USDT
              - UnderlyingName: INJ/USDT


        Pipeline:
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
  - name: qs-kucoinfut-210
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 209
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: ETH/USD
              - UnderlyingName: CFX/USDT
              - UnderlyingName: AUCTION/USDT
              - UnderlyingName: IOTX/USDT
              - UnderlyingName: JUP/USDT
              - UnderlyingName: PENDLE/USDT
              - UnderlyingName: NOT/USDT
              - UnderlyingName: BB/USDT
              - UnderlyingName: ENA/USDT
              - UnderlyingName: ALICE/USDT
              - UnderlyingName: MEW/USDT
              - UnderlyingName: BRETT/USDT
              - UnderlyingName: BOME/USDT
              - UnderlyingName: MERL/USDT
              - UnderlyingName: AEVO/USDT
              - UnderlyingName: W/USDT
              - UnderlyingName: TNSR/USDT
              - UnderlyingName: SLERF/USDT
        Pipeline:
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
  - name: qs-kucoinfut-211
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
    requests:
      cpu: 2000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 3000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      PriceServerClient:
        Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
      QuoteServer:
        ShardId: 210
        ExchangeName: KuCoinFut
        Monitor:
          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: OM/USDT
              - UnderlyingName: ETHFI/USDT
              - UnderlyingName: SAGA/USDT
              - UnderlyingName: PORTAL/USDT
              - UnderlyingName: ZEUS/USDT
              - UnderlyingName: OMNI/USDT
              - UnderlyingName: ENJ/USDT
              - UnderlyingName: TIA/USDT
              - UnderlyingName: PEPE/USDT
              - UnderlyingName: MEME/USDT
              - UnderlyingName: STMX/USDT
              - UnderlyingName: WLD/USDT
              - UnderlyingName: DODO/USDT
              - UnderlyingName: ASTR/USDT
              - UnderlyingName: HBAR/USDT
        Pipeline:
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: "23:00:00"
