apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJkZXBsb3lybyIsInBhc3N3b3JkIjoiZ2hwX1QwNmN1VTFIRXh1bGZoM1g0aUh5Y3dpb3FqNTN6czMxRWo0QSIsImF1dGgiOiJaR1Z3Ykc5NWNtODZaMmh3WDFRd05tTjFWVEZJUlhoMWJHWm9NMWcwYVVoNVkzZHBiM0ZxTlRONmN6TXhSV28wUVE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-creds
type: kubernetes.io/dockerconfigjson
