apiVersion: v1
kind: Service
metadata:
  name: position-service
  namespace: alc-position-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "position-service"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: position-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9250
      targetPort: ps-port
