QuoteServers:
  - name: qs-huobidm-212
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-huobi:2025.1.14.73-100f6ef
    requests:
      cpu: 1200m
      memory: 2000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
    nodeDestiny: dg-rt-az1
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az1
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      PriceServerClient:
        Address: ">tcp://qs-tokyo-12.node.al:10951,>tcp://qs-tokyo-12.node.al:10956,>tcp://qs-tokyo-13.node.al:10951,>tcp://qs-tokyo-13.node.al:10956,>tcp://qs-tokyo-14.node.al:10951"
      QuoteServer:
        ShardId: 211
        ExchangeName: HuobiDM
        PeriodicSnapshotTrigger:
          Enabled: true
          MinPeriodSeconds: 10
          MaxPeriodSeconds: 15
        FundingRatePoller:
          DelayBetweenPullsInSeconds: 10
        HuobiDM:
          Collocation: true
        Monitor:
          DefaultConnectionCount: 1
          MaxSymbolsPerConnection: 10
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: ETH/USD
                NamePatterns:
                - _Perpetual
              - UnderlyingName: LTC/USD
              - UnderlyingName: CHZ/USDT
              - UnderlyingName: BLUR/USDT
              - UnderlyingName: CORE/USDT
              - UnderlyingName: TON/USDT
              - UnderlyingName: MASK/USDT
              - UnderlyingName: CFX/USDT
              - UnderlyingName: WAVES/USDT
              - UnderlyingName: XRP/USDT
              - UnderlyingName: XRP/USD
              - UnderlyingName: EOS/USDT
              - UnderlyingName: ETC/USDT
              - UnderlyingName: AAVE/USDT
              - UnderlyingName: ADA/USDT
              - UnderlyingName: ALGO/USDT
              - UnderlyingName: JST/USDT
              - UnderlyingName: LINK/USD

        RateLimiter:
          Http:
            UsageLimit: 120
            Interval: 00:00:03
            MinAcquireGap: 0.00:00:00.075
            RequestCosts:
              FundingRate: 1
        Pipeline:
          Disruptor:
            DisruptorStatsDecoratorEnabled: false
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          AbArbitrator:
            DepthBookProcessing:
              OrderBy: Sequence
            TradesProcessing:
              OrderBy: Sequence
          SanityCheckFilter:
            AllowEmptyL2Deltas: true
          SnapshotCoordinator:
            OrderBy: Sequence
          DepthBookMaintainer:
            LevelsCap: 150
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-03:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        Enabled: false
  - name: qs-huobidm-213
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-huobi:2025.1.14.73-100f6ef
    requests:
      cpu: 1200m
      memory: 2000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
    nodeDestiny: dg-rt-az1
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az1
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      PriceServerClient:
        Address: ">tcp://qs-tokyo-12.node.al:10951,>tcp://qs-tokyo-12.node.al:10956,>tcp://qs-tokyo-13.node.al:10951,>tcp://qs-tokyo-13.node.al:10956,>tcp://qs-tokyo-14.node.al:10951"
      QuoteServer:
        ShardId: 212
        ExchangeName: HuobiDM
        PeriodicSnapshotTrigger:
          Enabled: true
          MinPeriodSeconds: 10
          MaxPeriodSeconds: 15
        FundingRatePoller:
          DelayBetweenPullsInSeconds: 10
        HuobiDM:
          Collocation: true
        Monitor:
          DefaultConnectionCount: 1
          MaxSymbolsPerConnection: 10

          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: DOT/USD
              - UnderlyingName: ADA/USD
              - UnderlyingName: OP/USDT
              - UnderlyingName: APT/USDT
              - UnderlyingName: SOL/USDT
              - UnderlyingName: FTM/USDT
              - UnderlyingName: IMX/USDT
              - UnderlyingName: SHIB/USDT
              - UnderlyingName: KAVA/USDT
              - UnderlyingName: GMT/USDT
              - UnderlyingName: GRT/USDT
              - UnderlyingName: SNX/USDT
              - UnderlyingName: THETA/USDT
              - UnderlyingName: DOGE/USD
              - UnderlyingName: TRX/USDT
                NamePatterns:
                - _Perpetual
              - UnderlyingName: BTC/USD
                NamePatterns:
                - _Perpetual
              - UnderlyingName: CRV/USDT
              - UnderlyingName: DOGE/USDT
              - UnderlyingName: LTC/USDT
              - UnderlyingName: WIN/USDT
              - UnderlyingName: ETH/USDT
              - UnderlyingName: AVAX/USDT
              - UnderlyingName: ATOM/USDT



        RateLimiter:
          Http:
            UsageLimit: 120
            Interval: 00:00:03
            MinAcquireGap: 0.00:00:00.075
            RequestCosts:
              FundingRate: 1
        Pipeline:
          Disruptor:
            DisruptorStatsDecoratorEnabled: false
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          AbArbitrator:
            DepthBookProcessing:
              OrderBy: Sequence
            TradesProcessing:
              OrderBy: Sequence
          SanityCheckFilter:
            AllowEmptyL2Deltas: true
          SnapshotCoordinator:
            OrderBy: Sequence
          DepthBookMaintainer:
            LevelsCap: 150
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-03:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        Enabled: false
  - name: qs-huobidm-214
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-huobi:2025.1.14.73-100f6ef
    requests:
      cpu: 1200m
      memory: 2000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
    nodeDestiny: dg-rt-az1
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az1
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      PriceServerClient:
        Address: ">tcp://qs-tokyo-12.node.al:10951,>tcp://qs-tokyo-12.node.al:10956,>tcp://qs-tokyo-13.node.al:10951,>tcp://qs-tokyo-13.node.al:10956,>tcp://qs-tokyo-14.node.al:10951"
      QuoteServer:
        ShardId: 213
        ExchangeName: HuobiDM
        PeriodicSnapshotTrigger:
          Enabled: true
          MinPeriodSeconds: 10
          MaxPeriodSeconds: 15
        FundingRatePoller:
          DelayBetweenPullsInSeconds: 10
        HuobiDM:
          Collocation: true
        Monitor:
          DefaultConnectionCount: 1
          MaxSymbolsPerConnection: 10

          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: BTC/USDT
              - UnderlyingName: BCH/USDT
              - UnderlyingName: LINK/USDT
              - UnderlyingName: FIL/USDT
              - UnderlyingName: DOT/USDT
              - UnderlyingName: BNB/USDT
              - UnderlyingName: YFI/USDT
              - UnderlyingName: UNI/USDT
              - UnderlyingName: ONEINCH/USDT
              - UnderlyingName: NEAR/USDT
              - UnderlyingName: MANA/USDT
              - UnderlyingName: KSM/USDT
              - UnderlyingName: LRC/USDT
              - UnderlyingName: SAND/USDT
              - UnderlyingName: AXS/USDT
              - UnderlyingName: DYDX/USDT
              - UnderlyingName: APE/USDT
              - UnderlyingName: SUSHI/USDT
              - UnderlyingName: TRX/USD
                NamePatterns:
                - _Perpetual
              - UnderlyingName: ARB/USDT

        RateLimiter:
          Http:
            UsageLimit: 120
            Interval: 00:00:03
            MinAcquireGap: 0.00:00:00.075
            RequestCosts:
              FundingRate: 1
        Pipeline:
          Disruptor:
            DisruptorStatsDecoratorEnabled: false
          Subsampling:
            BestBidOfferThreshold: 1e-5
            TimeThreshold: 00:00:01
            PriceForChangeThreshold: 3.0e-05
          AbArbitrator:
            DepthBookProcessing:
              OrderBy: Sequence
            TradesProcessing:
              OrderBy: Sequence
          SanityCheckFilter:
            AllowEmptyL2Deltas: true
          SnapshotCoordinator:
            OrderBy: Sequence
          DepthBookMaintainer:
            LevelsCap: 150
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-03:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        Enabled: false
