apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-ib-101
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-ib:2023.12.7.15-48e2be4
  replicas: 0
  destiny: dg-test
  cpu_request: 2000m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |-
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: IB
      ShardId: 100
      IB:
        IBAccountNumber: U3424407
        Host: colo-tokyo-test-prod2.node.al
        Port: 4003
        SessionId: 21
        MinPriceLevelsToInitialize: 8
        MinPriceLevelsToSend: 5
      Monitor:
        DefaultConnectionCount: 1
        Symbols:
          - Name: EUR/USD
          - Name: USD/MXN
          - Name: USD/SGD
      Pipeline:
        Disruptor:
          WaitStrategy: BusySpin
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-test:11800"

          V3BinaryFormat:
            DevelopmentMode: true   
                 
#        DepthBookMaintainer:
#          TickersNeedExchangeTime: true
