apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-mexc-305
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-mexc-v3:2024.3.25.105-fcfa5f6
  replicas: 1
  destiny: dg-nrt
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 304
      ExchangeName: Mexc
      Monitor:
        MaxSymbolsPerConnection: 10
        Symbols:
        - Name: MYRO/USDT
        - Name: NAKA/USDT
        - Name: NEAR/USDC
        - Name: NIBI/USDT
        - Name: NMR/USDT
        - Name: NYAN/USDT
        - Name: OKB/USDT
        - Name: OMG/USDT
        - Name: ONG/USDT
        - Name: OP/USDC
        - Name: ORDER/USDT
        - Name: PATEX/USDT
        - Name: PBUX/USDT
        - Name: PENG/USDT
        - Name: PEPE2/USDT
        - Name: PNG/USDT
        - Name: POND/USDT
        - Name: PONKE/USDT
        - Name: POPCAT/USDT
        - Name: PRCL/USDT
        - Name: PRQ/USDT
        - Name: PUFFER/USDT
        - Name: PYTH/USDT
        - Name: QI/USDT
        - Name: RARI/USDT
        - Name: RATS/USDT
        - Name: RAY/USDC
        - Name: NFP/USDT
        - Name: NFT/USDT
        - Name: NKN/USDT
        - Name: NOT/USDT
        - Name: NPC/USDT
        - Name: NS/USDT
        - Name: NTRN/USDT
        - Name: NULS/USDT
        - Name: OG/USDT
        - Name: OGN/USDT
        - Name: OMNI/USDT
        - Name: ONE/USDT
        - Name: ONT/USDT
        - Name: OP/USDT
        - Name: ORCA/USDT
        - Name: OSMO/USDT
        - Name: OXT/USDT
        - Name: PAXG/USDT
        - Name: PENDLE/USDT
        - Name: PEPE/USDT
        - Name: PERP/USDT
        - Name: PIXEL/USDT
        - Name: PNUT/USDT
        - Name: POL/USDT
        - Name: PORTAL/USDT
        - Name: PROS/USDT
        - Name: PYR/USDT
        - Name: QNT/USDT
        - Name: QTUM/USDT
        - Name: QUICK/USDT
        - Name: RACA/USDT
        - Name: RAD/USDT
        - Name: REI/USDT
        - Name: RENDER/USDT
        - Name: REZ/USDT
        - Name: ROSE/USDT
        - Name: RUNE/USDT
        - Name: RVN/USDT
        - Name: RWA/USDT
        - Name: SAGA/USDT
        - Name: SAND/USDT
        - Name: DAO/USDT
        - Name: PHB/USDT
        - Name: LIT/USDT
        - Name: BICO/USDT
        - Name: SXP/USDT
        DefaultConnectionCount: 1
        RateLimiter:
          Http:
            UsageLimit: 240
            Interval: 00:01
            MinAcquireGap: 0.00:00:01
            RequestCosts:
              Snapshot: 15
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-collect:11800"
          V3BinaryFormat:
            DevelopmentMode: false
