apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-mexc-304
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-mexc-v3:2024.3.25.105-fcfa5f6
  replicas: 1
  destiny: dg-nrt
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 303
      ExchangeName: Mexc
      Monitor:
        MaxSymbolsPerConnection: 10
        Symbols:
        - Name: JST/USDT
        - Name: KARRAT/USDT
        - Name: KAS/USDT
        - Name: KDA/USDT
        - Name: KISHU/USDT
        - Name: KMNO/USDT
        - Name: L3/USDT
        - Name: LAI/USDT
        - Name: LOKA/USDT
        - Name: LTC/USDC
        - Name: LUNC/USDC
        - Name: MANEKI/USDT
        - Name: MASA/USDT
        - Name: MAVIA/USDT
        - Name: MDT/USDT
        - Name: METIS/USDT
        - Name: MEW/USDT
        - Name: MINA/USDC
        - Name: MOBILE/USDT
        - Name: MODE/USDT
        - Name: MOG/USDT
        - Name: MON/USDT
        - Name: MOODENG/USDT
        - Name: MOTHER/USDT
        - Name: MUBI/USDT
        - Name: JTO/USDT
        - Name: JUP/USDT
        - Name: KAVA/USDT
        - Name: KNC/USDT
        - Name: LADYS/USDT
        - Name: LDO/USDT
        - Name: LEVER/USDT
        - Name: LINA/USDT
        - Name: LINK/USDT
        - Name: LL/USDT
        - Name: LOOKS/USDT
        - Name: LOOM/USDT
        - Name: LPT/USDT
        - Name: LQTY/USDT
        - Name: LRC/USDT
        - Name: LTC/USDT
        - Name: LUNC/USDT
        - Name: MAGIC/USDT
        - Name: MANA/USDT
        - Name: MASK/USDT
        - Name: MAV/USDT
        - Name: MAX/USDT
        - Name: MBL/USDT
        - Name: ME/USDT
        - Name: MEME/USDT
        - Name: MEMETOON/USDT
        - Name: MERL/USDT
        - Name: MICHI/USDT
        - Name: MINA/USDT
        - Name: MKR/USDT
        - Name: MNT/USDT
        - Name: MONKY/USDT
        - Name: MORPHO/USDT
        - Name: MOVE/USDT
        - Name: MOVR/USDT
        - Name: MVL/USDT
        - Name: MYRIA/USDT
        - Name: NEAR/USDT
        - Name: NEO/USDT
        - Name: SATS/USDT
        - Name: CVX/USDT
        - Name: RAY/USDT
        - Name: SOL/USDT
        - Name: HIFI/USDT
        - Name: RSR/USDT
        - Name: AR/USDT
        - Name: MANTA/USDT
        - Name: KSM/USDT
        DefaultConnectionCount: 1
        RateLimiter:
          Http:
            UsageLimit: 240
            Interval: 00:01
            MinAcquireGap: 0.00:00:01
            RequestCosts:
              Snapshot: 15
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-collect:11800"
          V3BinaryFormat:
            DevelopmentMode: false
