apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-coinone-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-coinone:2024.1.10.24-c375899
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: Coinone

      Coinone:
        ConnectionIdleInterval: 00:20:00

      CheckStaleMarketDataTrigger:
        Interval: 00:00:01

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 1
        Symbols:
          - Name: BEL/KRW
          - Name: PROM/KRW
          - Name: FET/KRW
          - Name: DIA/KRW
          - Name: FRONT/KRW
          - Name: DODO/KRW
          - Name: BORA/KRW
          - Name: ONEINCH/KRW
          - Name: MBL/KRW
          - Name: AAVE/KRW
          - Name: WNCG/KRW
          - Name: ACH/KRW
          - Name: SIX/KRW
          - Name: UMA/KRW
          - Name: ADA/KRW
          - Name: ONT/KRW
          - Name: SXP/KRW
          - Name: BTG/KRW
          - Name: DOT/KRW
          - Name: GAS/KRW
          - Name: SKLAY/KRW
          - Name: EGG/KRW
          - Name: INJ/KRW
          - Name: XDATA/KRW
          - Name: ALPHA/KRW
          - Name: ONG/KRW
          - Name: AVAX/KRW
          - Name: GRT/KRW
          - Name: SEI/KRW
          - Name: BTC/KRW
          - Name: EVER/KRW
          - Name: AXS/KRW
          - Name: HPO/KRW
          - Name: TAIKO/KRW
          - Name: TON/KRW
          - Name: ENA/KRW
          - Name: MINA/KRW
          - Name: ETHFI/KRW
          - Name: ENS/KRW
          - Name: HOT/KRW
          - Name: HBAR/KRW
      RateLimiter:
        Http:
          UsageLimit: 3000
          Interval: 00:01
          MinAcquireGap: 0.00:00:00.2
          RequestCosts:
            Snapshot: 10
      Pipeline:
        DepthBookMaintainer:
          LevelsCap: 150
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 01:00:00
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sel-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
