apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-coinone-203
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-coinone:2023.6.27.38-c6655b0e9ed4e467e9d091554fa2d1a9e4ec878b
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 202
      ExchangeName: Coinone

      Coinone:
        ConnectionIdleInterval: 00:20:00

      CheckStaleMarketDataTrigger:
        Interval: 00:00:01

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 1
        Symbols:
          - Name: ORC/KRW
          - Name: QTCON/KRW
          - Name: AMO/KRW
          - Name: DVI/KRW
          - Name: CKB/KRW
          - Name: CTSI/KRW
          - Name: ARPA/KRW
          - Name: STPT/KRW
          - Name: TEMCO/KRW
          - Name: MVC/KRW
          - Name: CRV/KRW
          - Name: ASM/KRW
          - Name: IOTX/KRW
          - Name: HIBS/KRW
          - Name: COS/KRW
          - Name: PHA/KRW
          - Name: MLK/KRW
          - Name: FIL/KRW
          - Name: SOL/KRW
          - Name: XEC/KRW
          - Name: ETC/KRW
          - Name: EOS/KRW
          - Name: WEMIX/KRW
          - Name: JTO/KRW
          - Name: BTT/KRW
          - Name: PYTH/KRW
          - Name: KAS/KRW
          - Name: MEME/KRW
          - Name: PIB/KRW
          - Name: ETH/KRW
          - Name: DOGE/KRW
          - Name: KLAY/KRW
          - Name: KSM/KRW
          - Name: SEILOR/KRW
          - Name: BSV/KRW
          - Name: GALA/KRW
          - Name: ZETA/KRW
          - Name: MAVIA/KRW
          - Name: WLD/KRW
          - Name: PEPE/KRW
          - Name: BONK/KRW
          - Name: MANTA/KRW
          - Name: STRK/KRW
          - Name: NEAR/KRW
          - Name: ARB/KRW
          - Name: W/KRW
          - Name: PCI/KRW
          - Name: MNT/KRW
          - Name: JUP/KRW
          - Name: STG/KRW
          - Name: PENDLE/KRW
          - Name: MEW/KRW
      RateLimiter:
        Http:
          UsageLimit: 3000
          Interval: 00:01
          MinAcquireGap: 0.00:00:00.2
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        DepthBookMaintainer:
          LevelsCap: 150
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 01:00:00
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sel-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
