apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: csi-gp3-custom-5000-250