apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-gateio-305
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-gateio:2024.1.10.31-c375899
  replicas: 1
  destiny: dg-test
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 304
      ExchangeName: GateIO
      GateIO:
        ExchangeConnection:
          WebsocketApi:
            Uri: wss://spotws-private.gateapi.io/ws/v4/
        SnapshotMakerStrategy:
          RestApi:
            Uri: "https://apiv4-private.gateapi.io/api/v4/spot/order_book"
      Monitor:
        Symbols:
        - Name: PUMP/USDT
        - Name: PUNDU/USDT
        - Name: PUNKAI/USDT
        - Name: PUSH/USDT
        - Name: QKC/USDT
        - Name: QORPO/USDT
        - Name: RADAR/USDT
        - Name: RANKER/USDT
        - Name: RAZOR/USDT
        - Name: RBC/USDT
        - Name: REAP/USDT
        - Name: RENDER/USDT
        - Name: REP/USDT
        - Name: REQ/USDT
        - Name: REVU/USDT
        - Name: REVV/USDT
        - Name: REX/USDT
        - Name: REZ/USDT
        - Name: RGAME/USDT
        - Name: RIDE/USDT
        - Name: RINGAI/USDT
        - Name: ROCK/USDT
        - Name: ROCO/USDT
        - Name: ROOST/USDT
        - Name: ROUTE/USDT
        - Name: RTF/USDT
        - Name: RWA/USDT
        - Name: SAFE/USDT
        - Name: SAGA/USDT
        - Name: SAI/USDT
        - Name: SAMO/USDT
        - Name: SCA/USDT
        - Name: SCR/USDT
        - Name: SD/USDT
        - Name: SEAM/USDT
        - Name: SECOND/USDT
        - Name: SEND/USDT
        - Name: SENSO/USDT
        - Name: SERO/USDT
        - Name: SERSH/USDT
        - Name: SFM/USDT
        - Name: SFP/USDT
        - Name: SHDW/USDT
        - Name: SHIRO/USDT
        - Name: SHPING/USDT
        - Name: SIX/USDT
        - Name: SKYA/USDT
        - Name: SLERF/USDT
        - Name: SLN/USDT
        - Name: SMART/USDT
        - Name: SMX/USDT
        - Name: SNAP/USDT
        - Name: SNS/USDT
        - Name: SNT/USDT
        - Name: SOIL/USDT
        - Name: SOL/USDC
        - Name: SONIC/USDT
        - Name: SOON/USDT
        - Name: SOPH/USDT
        - Name: SOVRN/USDT
        - Name: SPACE/USDT
        - Name: SPEC/USDT
        - Name: SPELLFIRE/USDT
        - Name: SPOT/USDT
        - Name: SPX/USDT
        - Name: SQD/USDT
        - Name: SRK/USDT
        - Name: SS20/USDT
        - Name: SSNC/USDT
        - Name: STBU/USDT
        - Name: STEEM/USDT
        - Name: STETH/USDT
        - Name: STMX/USDT
        - Name: STORM/USDT
        - Name: STREAM/USDT
        - Name: STRK/USDT
        - Name: STRM/USDT
        - Name: STRUMP/USDT
        - Name: SUI/USDC
        - Name: SUIA/USDT
        - Name: SUIAI/USDT
        - Name: SUN/USDT
        - Name: SWCH/USDT
        - Name: SWRV/USDT
        - Name: SYNC/USDT
        - Name: TABOO/USDT
        - Name: TAI/USDT
        - Name: TAIKO/USDT
        - Name: TALK/USDT
        - Name: TET/USDT
        - Name: THE/USDT
        - Name: THG/USDT
        - Name: THN/USDT
        - Name: TIP/USDT
        - Name: TNSR/USDT
        - Name: TOMS/USDT
        - Name: TRIO/USDT
        - Name: TRR/USDT
        - Name: TRUF/USDT
        - Name: TRUMP/USDT
        DefaultConnectionCount: 1
      Pipeline:
        SanityCheckFilter:
          AllowEmptyL2Deltas: true
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-collect:11800"
          V3BinaryFormat:
            DevelopmentMode: false
