apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: false

      Workflow:
        Type: SplitBySymbolCount
        SymbolsCount: 600
        InitialWorkflowCount: 4
    
      ZmqTransport:
        Endpoint:
          - ">tcp://qs-sing.node.al:10951"
          - ">tcp://qs-sing-2.node.al:10951"
          - ">tcp://qs-sing-3.node.al:10951"
        LocalByteCacheSize: 65536
        ReceiveHighWatermark: 300000
      
     
    Subscription:
      Prefix: ""
      ExporterName: "qs-exporter-sin-python"
      Exchanges:
        - "CurrencyDataFeed"
        - "LFQS"

kind: ConfigMap
metadata:
  name: qs-exporter-config-python
