apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-woox-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-woox:2024.12.6.68-0146c75
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1100m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: WooX

      Monitor:
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: ETH/USDT
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: BTC/USDT
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: SOL/USDT
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: SUI/USDT
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: DOGE/USDT
              NamePatterns:
                - '_Perpetual'
        DefaultConnectionCount: 3

      Pipeline:
        AbArbitrator:
          DepthBookProcessing:
            OrderBy: Timestamp
          TradesProcessing:
            OrderBy: Timestamp
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
          V3BinaryFormat:
            DevelopmentMode: false
