apiVersion: v1
data:
  config.yaml: |-
    mesh:
      default_region: sing
      consul_endpoint: "http://consul-server.consul:8500"
      consul_token: "a514908a-58e7-c4f1-f041-a096cd061ba1"

    dg_proxy:
      intra_only_mode: true
      dg_id: 66
      in_port: 11800
      out_port: 11900
      high_water_mark: 200000
      monitor: false
    
    prometheus:
      port: 5000
      metrics_path: /metrics
      dg_name: dg-collect

kind: ConfigMap
metadata:
  name: dg-proxy-config

