apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      ZmqTransport:
        Endpoint:
          - ">tcp://dg-proxy.dg-irl-01:11900"
    DataRecorder:
      PublishFileEventChannel:
        ParallelConsumers: 2
      S3Options:
        Bucket: "qs-bin-v2-irl"
      Redis:
        Host: elasticache-trading-platform-irl.tudwfp.ng.0001.euw1.cache.amazonaws.com

kind: ConfigMap
metadata:
  name: data-recorder-config
