---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: alc-broadcaster-secret-store
  namespace: defi
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: alc-broadcaster-secret-store-sa
