apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-test
  namespace: test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-test
  template:
    metadata:
      labels:
        app: httpbin-test
    spec:
      containers:
      - name: httpbin-test
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
