apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoin-218
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.10.73-b526a2d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: KuCoin
      ShardId: 217
      KuCoin:
        ApiPassphrase: UPpdoXnVJeJjAx9HzYGbmeG2hmlhJuAf
        ApiKey: 6672b0bd5ee2e4000139e38b
        ApiSecret: a87e98dd-04ff-4be1-af42-337dee963d6f
      CheckStaleMarketDataTrigger:
        Interval: 00:00:01
      Monitor:
        Symbols:
          - Name: BOSON/USDT
          - Name: EDU/USDT
          - Name: SSV/USDT
          - Name: CELR/USDT
          - Name: KAGI/USDT
          - Name: MLK/USDT
          - Name: BICO/USDT
          - Name: WLKN/USDT
          - Name: HFT/USDC
          - Name: VRTX/USDT
          - Name: BAL/USDT
          - Name: XTAG/USDT
          - Name: ACQ/USDT
          - Name: PIX/USDT
          - Name: RLC/USDT
          - Name: UFO/USDT
          - Name: ETH/EUR
          - Name: CCD/USDT
          - Name: ANALOS/USDT
          - Name: MYRO/USDT
          - Name: MNT/USDT
          - Name: MOBILE/USDT
          - Name: XYM/USDT
          - Name: ERTHA/USDT
          - Name: XAI/USDT
          - Name: ZKF/USDT
          - Name: APP/USDT
          - Name: SYN/USDT
          - Name: SCPT/USDT
          - Name: MV/USDT
          - Name: RAY/USDT
          - Name: NIM/USDT
          - Name: PRQ/USDT
          - Name: BNB/USDC
          - Name: GLQ/USDT
          - Name: STORE/USDT
          - Name: EPIK/USDT
          - Name: BNC/USDT
          - Name: ONDO/USDT
          - Name: MANTA/USDT
          - Name: COQ/USDT
          - Name: WIF/USDT
          - Name: XEM/USDT
          - Name: LTC/USDC
          - Name: UNB/USDT
          - Name: OUSD/BTC
          - Name: HOTCROSS/USDT
          - Name: MXM/USDT
          - Name: SCLP/USDT
          - Name: MIND/USDT
      RateLimiter:
        Http:
          UsageLimit: 200
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.10
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"
          V3BinaryFormat:
            DevelopmentMode: false
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 00:02:00
    PerfCollector:
      HistogramDumpInterval: "23:00:00"
