apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoin-215
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1100m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: KuCoin
      ShardId: 214

      CheckStaleMarketDataTrigger:
        Interval: 00:00:01
      Monitor:
        Symbols:
          - Name: ELON/USDT
          - Name: TIDAL/USDT
          - Name: ONEINCH/USDT
          - Name: TFUEL/USDT
          - Name: NEO/USDT
          - Name: BSV/USDT
          - Name: ID/USDT
          - Name: LRC/USDT
          - Name: FLOW/USDT
          - Name: DREAMS/USDT
          - Name: NGL/USDT
          - Name: BCH/USDC
          - Name: BCH/USDT
          - Name: NEAR/BTC
          - Name: NEAR/USDT
          - Name: OMG/USDT
          - Name: POLYX/USDT
          - Name: IDEA/USDT
          - Name: JUP/USDT
          - Name: GTAI/USDT
          - Name: WEN/USDT
          - Name: DEFI/USDT
          - Name: DMAIL/USDT
          - Name: LBR/USDT
          - Name: BMX/USDT
          - Name: MAV/USDT
          - Name: LQTY/USDT
          - Name: BURGER/USDT
          - Name: BRISE/USDT
          - Name: XCV/USDT
          - Name: BOBA/USDT
          - Name: TRAC/USDT
          - Name: AOG/USDT
          - Name: FIDA/USDT
          - Name: AUCTION/USDT
          - Name: LPT/USDT
          - Name: NAVX/USDT
          - Name: FORTH/USDT
          - Name: IRL/USDT
          - Name: ALPHA/USDT
          - Name: BSW/USDT
          - Name: ICX/USDT
          - Name: BOME/USDT
          - Name: DOGE/USDT
          - Name: DOGE/BTC
          - Name: DOGE/USDC
          - Name: LDO/USDT
          - Name: REQ/USDT
          - Name: ROOT/USDT
      RateLimiter:
        Http:
          UsageLimit: 200
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.10
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: "00:00:01"
          PriceForChangeThreshold: 3.0e-5
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"
          V3BinaryFormat:
            DevelopmentMode: false
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 00:02:00
    PerfCollector:
      Enabled: false
