apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoin-217
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.75-ef5ef9d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1100m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: KuCoin
      ShardId: 216
      Monitor:
        Symbols:
          - Name: SATS/USDT
          - Name: JTO/USDT
          - Name: QI/USDT
          - Name: SNS/USDT
          - Name: XRD/USDT
          - Name: INSP/USDT
          - Name: WORK/USDT
          - Name: MYRIA/USDT
          - Name: OSMO/USDT
          - Name: BTC/DAI
          - Name: LAI/USDT
          - Name: WEMIX/USDT
          - Name: INJ/BTC
          - Name: AURORA/USDT
          - Name: AIPAD/USDT
          - Name: GGG/USDT
          - Name: SCRT/USDT
          - Name: XAVA/USDT
          - Name: TURBOS/USDT
          - Name: CSIX/USDT
          - Name: GAFI/USDT
          - Name: AMPL/USDT
          - Name: WHALE/USDT
          - Name: BTC/EUR
          - Name: BDX/BTC
          - Name: FCON/USDT
          - Name: CETUS/USDT
          - Name: RPK/USDT
          - Name: ARKM/USDT
          - Name: SUIP/USDT
          - Name: TRX/ETH
          - Name: PROM/USDT
          - Name: WAN/BTC
          - Name: DCR/USDT
          - Name: RATS/USDT
          - Name: ARTY/USDT
          - Name: MTS/USDT
          - Name: GNS/USDT
          - Name: STG/USDT
          - Name: XYO/USDT
          - Name: DENT/USDT
          - Name: CEEK/USDT
          - Name: MUBI/USDT
      RateLimiter:
        Http:
          UsageLimit: 200
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.10
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: "00:00:01"
          PriceForChangeThreshold: 3.0e-5
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"
          V3BinaryFormat:
            DevelopmentMode: false
