apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoin-214
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: KuCoin
      ShardId: 213
      CheckStaleMarketDataTrigger:
        Interval: 00:00:01
      Monitor:
        Symbols:
          - Name: GMM/USDT
          - Name: KAI/USDT
          - Name: WOOP/USDT
          - Name: CYBER/USDT
          - Name: OLT/USDT
          - Name: TIA/USDT
          - Name: ORDI/USDT
          - Name: BIGTIME/USDT
          - Name: PEPE/USDT
          - Name: TRB/USDT
          - Name: STND/USDT
          - Name: MTRG/USDT
          - Name: BAT/USDT
          - Name: CWS/USDT
          - Name: LYM/USDT
          - Name: CREAM/USDT
          - Name: NKN/USDT
          - Name: OXT/USDT
          - Name: CKB/USDT
          - Name: ETH/DAI
          - Name: LAYER/USDT
          - Name: MELOS/USDT
          - Name: NOM/USDT
          - Name: HEART/USDT
          - Name: ZCX/USDT
          - Name: BDX/USDT
          - Name: IOTA/USDT
          - Name: OBI/USDT
          - Name: DCK/USDT
          - Name: HIGH/USDT
          - Name: HYDRA/USDT
          - Name: VOXEL/USDT
          - Name: POKT/USDT
          - Name: NUM/USDT
          - Name: XEN/USDT
      RateLimiter:
        Http:
          UsageLimit: 200
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.10
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: "00:00:01"
          PriceForChangeThreshold: 3.0e-5
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"
          V3BinaryFormat:
            DevelopmentMode: false
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 00:02:00
    PerfCollector:
      HistogramDumpInterval: "23:00:00"

