apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoin-216
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: KuCoin
      ShardId: 215

      CheckStaleMarketDataTrigger:
        Interval: 00:00:01
      Monitor:
        Symbols:
          - Name: AUDIO/USDT
          - Name: RUNE/USDT
          - Name: NGC/USDT
          - Name: XDC/BTC
          - Name: XDC/USDT
          - Name: XDC/ETH
          - Name: XCN/USDT
          - Name: VSYS/BTC
          - Name: KLV/USDT
          - Name: CHZ/USDT
          - Name: SENSO/USDT
          - Name: RVN/USDT
          - Name: MXC/USDT
          - Name: SYLO/USDT
          - Name: GTC/USDT
          - Name: AA/USDT
          - Name: TAO/USDT
          - Name: TURT/USDT
          - Name: OP/USDC
          - Name: USDJ/USDT
          - Name: VIDT/USDT
          - Name: LOKA/USDT
          - Name: ELF/USDT
          - Name: RPL/USDT
          - Name: WELL/USDT
          - Name: 1CAT/USDT
          - Name: OFN/USDT
          - Name: ALEX/USDT
          - Name: PENDLE/USDT
          - Name: TARA/USDT
          - Name: NFP/USDT
          - Name: SAROS/USDT
          - Name: PUSH/USDT
          - Name: ZETA/USDT
          - Name: MAVIA/USDT
          - Name: DYM/USDT
          - Name: LENDS/USDT
          - Name: QUICK/USDT
          - Name: ISLM/USDT
          - Name: BONDLY/USDT
          - Name: DAR/USDT
          - Name: OAS/USDT
          - Name: CKB/BTC
          - Name: SYS/USDT
          - Name: POLC/USDT
          - Name: DOT/BTC
          - Name: AURY/USDT
      RateLimiter:
        Http:
          UsageLimit: 200
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.10
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: "00:00:01"
          PriceForChangeThreshold: 3.0e-5
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"
          V3BinaryFormat:
            DevelopmentMode: false
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 00:02:00
    PerfCollector:
      Enabled: false


