apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-ib-101
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-ib:2024.2.12.20-53a3bce
  replicas: 0
  destiny: dg-rt
  cpu_request: 1100m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |-
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: IB
      ShardId: 100
      IB:
        IBAccountNumber: U3424407
        Host: colo-tokyo-test-prod2.node.al
        Port: 4003
        SessionId: 23
        MinPriceLevelsToInitialize: 5
        MinPriceLevelsToSend: 4
      Monitor:
        DefaultConnectionCount: 1
        Symbols:
          - Name: EUR/USD 
          - Name: XAU/USD
          - Name: XAG/USD
          #- Name: USD/MXN
          #- Name: USD/SGD
      Pipeline:
        DepthBookMaintainer:
          LevelsCap: 5
        Disruptor:
          WaitStrategy: BusySpin
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sin-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false   
                 