QuoteServers:
  - name: qs-bigone-201
    image: ghcr.io/alphalab-hq/alc-qs-exchange-bigone:2022.1.24.16-c30513c7aff20050e6155f35e960b0e2f109dbad
    requests:
      cpu: 1000m
      memory: 2000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true
      QuoteServer:
        ShardId: 200
        ExchangeName: BigONE
        Monitor:
          Symbols:
            - Name: BTC/USDT
            - Name: ETH/USDT
            - Name: XRP/USDT
            - Name: EOS/USDT
            - Name: ATOM/USDT
            - Name: DOT/USDT
            - Name: HOT/USDT
            - Name: LTC/USDT
            - Name: BCH/USDT
            - Name: ETC/USDT
            - Name: ZEC/USDT
            - Name: DASH/USDT
            - Name: XMR/USDT
            - Name: SHIB/USDT
            - Name: SOL/USDT
            - Name: TRX/USDT
            - Name: LTC/BTC
            - Name: QTUM/USDT
            - Name: APE/USDT
          DefaultConnectionCount: 1
        Pipeline:
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-04:11800"
            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: 24:00:00
