apiVersion: v1
data:
  config.yaml: |
    SecurityMaster:
      RefreshIntervalInSeconds: 1800
      FileLoader:
        CurrencyFilePath: /etc/security_master/security_master.ccy.yaml.latest
        ExchangesFilePath: /etc/security_master/security_master.exch.yaml.latest
        LoadAllSecuritiesDataFiles: true
        SecuritiesDataFilesPath: /etc/security_master
      
    QsClient:
      SecMasterThrottling:
          IsEnabled: true
          SilentPeriod: 00:05:00
      ZmqTransport:
        Endpoint:
          - ">tcp://qs-sing.node.al:10951"
          - ">tcp://qs-sing-2.node.al:10951"
          - ">tcp://qs-sing-3.node.al:10951"

    Diagnostics:
      DumpInterval: "00:15:00"

    PriceServer:
      PrimaryQuoteCurrency: "USD"
      ExchangesToSubscribe:
        - "AlcInternal"
        - "Backpack"
        - "BigONE"
        - "Binance"
        - "BinanceUS"
        - "BitBank"
        - "bitFlyer"
        - "Bitget"
        - "Bithumb"
        - "Bitstamp"
        - "BtcTurk"
        - "BybitSpot"
        - "CoinGecko"
        - "Coinone"
        - "CryptoCom"
        - "CurrencyDataFeed"
        - "DeribitSpot"
        - "Exmo"
        - "FMFWio"
        - "GateIO"
        - "GDAX"
        - "HitBTC"
        - "HuobiGlobal"
        - "IB"
        - "Icrypex"
        - "IndoDAX"
        - "Korbit"
        - "Kraken"
        - "KuCoin"
        - "Mexc"
        - "OKCoinJP"
        - "OKEx"
        - "Poloniex"
        - "Upbit"
        - "WooXSpot"
      ElementaryPriceTimeToLive: 00:05:00

      CurrencyAliases:
        BTC: ["HBTC", "BTCB", "WBTC", "XBT", "BTCBAVAX", "BTC.b", "cbBTC"]
        POL: ["WPOL"]
        BNB: ["WBNB"]
        ETH: ["WETH"]
        SOL: ["WSOL"]
        TRX: ["WTRX"]
        HC: ["HSR"]
        DAI: ["XDAI"]
        FTM: ["WFTM"]
        AVAX: ["WAVAX"]
        CRO: ["WCRO"]
        ONE: ["WONE"]
        MATIC: ["WMATIC"]
        LUNA: ["WLUNA", "LUNA2"]
        USDC: ["USDCEARB", "USDC.e", "USDCeth", "USDbC"]
        SEI: ["LDSEI"]
        API3: ["LDAPI3"]
        IMX: ["WIMX"]
        WEETH: ["WEETH.mode"]
      CurrencyMultiplicities:
        KSHIB:
          Base: "SHIB"
          Multiplier: 1000.0
      ReputableSources:
        usdt:
          - [ "Binance", "USDC" ]
          - [ "OKEx", "USDC" ]
          - [ "Kraken", "USD" ]
        default:
          - [ "Binance", "USDT" ]
          - [ "GDAX", "USD" ]
          - [ "OKEx", "USDT" ]
          - [ "KuCoin", "USDT" ]
          - [ "GateIO", "USDT" ]
          - [ "Mexc", "USDT" ]    
          - [ "HuobiGlobal", "USDT" ]
          - [ "IB", "SGD" ]
          - [ "IB", "MXN" ]
          - [ "IB", "EUR" ]
          - [ "CurrencyDataFeed", "USD" ]
          - [ "CurrencyDataFeed", "ARS" ]
          - [ "CurrencyDataFeed", "BRL" ]
          - [ "CurrencyDataFeed", "CHF" ]
          - [ "CurrencyDataFeed", "IDR" ]
          - [ "CurrencyDataFeed", "JPY" ]
          - [ "CurrencyDataFeed", "KRW" ]
          - [ "CurrencyDataFeed", "MXN" ]
          - [ "CurrencyDataFeed", "NZD" ]
          - [ "CurrencyDataFeed", "RUB" ]
          - [ "CurrencyDataFeed", "SGD" ]
          - [ "CurrencyDataFeed", "UAH" ]
          - [ "CurrencyDataFeed", "ZAR" ]
      FixedPriceCurrencies:
        POINT: 0
        DON: 0
        CHI: 0.0984
        EDG: 0.0238
        BMX: 0
        SUSHIBEAR: 0
        ETH3L: 0
        TONC: 0
        LTCUP: 0
        ANY: 0
        EPS: 0
        DEFI: 0
        ALGOBULL: 0
        SAITAMA: 0
        RINGX: 0
        BTTC: 0
        LUNC: 0
        CWD: 0
        RAMP: 0
        BSV3S: 0
        BSV3L: 0
        LOL: 0
        NAV: 0
        HUSD: 0
        UNI2S: 0
        ZEC3S: 0
        ZEC3L: 0
        RGT: 0
        LTCBEAR: 0
        GXC: 0
        XRPBEAR: 0
        BCH3L: 0
        LINKBULL: 0
        EOS3L: 0
        BCH3S: 0
        CYCLUB: 0
        LTCBULL: 0
        DOT2S: 0
        XRP3S: 0
        ETH1S: 0
        XRPBULL: 0
        ETH3S: 0
        EOS3S: 0
        TRXBULL: 0
        BTCBEAR: 0
        DOTUP: 0
        ETHBEAR: 0
        EOSBULL: 0
        FIL3S: 0
        FIL3L: 0
        DOTDOWN: 0
        XRP3L: 0
        BTC1S: 0
        BTC3L: 0
        UNI2L: 0
        DOT2L: 0
        LINK3L: 0
        LINK3S: 0
        BTC3S: 0
        TRXUP: 0
        LTC3S: 0
        LTC3L: 0
        OGV: 0
        ETHF: 0
        APENFT: 0
        AQUA: 0
        ICZ: 0
        PEARL: 0
        TALK: 0
        RIFI: 0
        ALBT: 0
        NANO: 0
        BTCST: 0
        EXRD: 0
        LTX: 0
        GTO: 0
        BCC: 0
        HPT: 0
        XSR: 0
        AWO: 0
        MFT: 0
        PGALA: 0
        RPG: 0
        SOC: 0
        AURY: 0
        ANW: 0
        CMT: 0
        YEE: 0
        1SOL: 0
        AION: 0
        NEBL: 0
        XRPDOWN: 0
        XRPUP: 0
        BASIC: 0
        CENNZ: 0
        DAD: 0
        COCOS: 0
        NORD: 0
        DDX: 0
        AUTO: 0
        BCD: 0
        DNT: 0
        SHPING: 0
        FOX: 0
        TMTG: 0
        UMB: 0
        KOK: 0
        SEELE: 0
        SRK: 0
        GO: 0
        XWG: 0
        PURE: 1
        NFUP: 1
        ATOLO: 0
        XCORE: 0
        MSB: 0
        NOA: 0
        BIT: 0
        HPO: 0
        MCH: 0
        APIX: 0
        TRUE: 0
        ADAUP: 0
        ADADOWN: 0
        SNM: 0
        RING: 0
        NU: 0
        FXDX: 0.05
        WINT: 0
        ONSTON: 0
        ANML: 0
        AZY: 0
        BOSON: 0
        BTRST: 0
        BUY: 0
        COVAL: 0
        DBC: 0
        DORA: 0
        GNX: 0
        GOLD: 0
        HEGIC: 0
        HOTCROSS: 0
        INSUR: 0
        INV: 0
        KAR: 0
        KEEP: 0
        MITH: 0
        NEW: 0
        O3: 0
        OMI: 0
        ONX: 0
        POSI: 0
        REPV2: 0
        SDN: 0
        SKM: 0
        SLC: 0
        STEP: 0
        TORN: 0
        TRIBE: 0
        XYO: 0
        CGG: 0
        BUSD: 0
        ZELIX: 0
        DFA: 0
        UNIC: 0
        NTVRK: 0
        HANDY: 0
        LDN: 0
        DFX: 0
        DIS: 0
        USH: 0
        PLA: 0
        ZBC: 0
        QRDO: 0
        WTC: 0
        GF: 0
        CATCH: 0
        POWER: 0
        EM: 0
        RFOX: 0
        MAP: 0
        CQT: 0
        NOIA: 0
        CRPT: 0
        STARLY: 0
        FORM: 0
        ANT: 0
        CUDOS: 0
        WMT: 0
        YLD: 0
        KLAY: 0
        VV: 0
        ORN: 0
        EDEN: 0
        STC: 0
        PIT: 0
        MRST: 0
        FLX: 0
        TXA: 0
        KTC: 0
        IDRT: 0
        JPG: 0
        NADA: 0
        PEL: 0
        SCLP: 0
        BFUSD: 1
        

    Publication:
      ShardId: 200
      Interval: 00:00:02
      Endpoints:
        - ">tcp://qs-sing.node.al:10950"
        - ">tcp://qs-sing-2.node.al:10950"
        - ">tcp://qs-sing-3.node.al:10950"

    V3BinaryFormat:
      DevelopmentMode: false

    Snapshot:
      SaveInterval: 00:15:00
      Path: "/s3_upload/alphalab-data/third_party_data/LFQS/"


kind: ConfigMap
metadata:
  name: alc-price-server-config
  namespace: alc-price-server
