apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bybit-210
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-bybit:2023.7.7.68-2c9aa5507b3888b4113ef3a17774d056fa02c94e

  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 209
      ExchangeName: Bybit

      Monitor:
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: LPT/USDT
            - UnderlyingName: EGLD/USDT
            - UnderlyingName: IOTX/USDT
            - UnderlyingName: ONEINCH/USDT
            - UnderlyingName: ALGO/USDT
            - UnderlyingName: ONE/USDT
            - UnderlyingName: DOGE/USDT
            - UnderlyingName: KSM/USDT
            - UnderlyingName: FTM/USDT
            - UnderlyingName: LOOKS/USDT
            - UnderlyingName: BAT/USDT
            - UnderlyingName: UNI/USDT
            - UnderlyingName: CRV/USDT
            - UnderlyingName: PEOPLE/USDT
            - UnderlyingName: AVAX/USDT
            - UnderlyingName: C98/USDT
            - UnderlyingName: SAND/USDT
            - UnderlyingName: RPL/USDT
            - UnderlyingName: FLR/USDT
            - UnderlyingName: BOBA/USDT
            - UnderlyingName: HOT/USDT
            - UnderlyingName: BEL/USDT
            - UnderlyingName: BAKE/USDT
            - UnderlyingName: BAND/USDT
            - UnderlyingName: REN/USDT
            - UnderlyingName: ICX/USDT
            - UnderlyingName: REEF/USDT
            - UnderlyingName: KLAY/USDT
            - UnderlyingName: BTC/USDT
            - UnderlyingName: UNFI/USDT
            - UnderlyingName: FLM/USDT


          DefaultConnectionCount: 2
          MaxSymbolsPerConnection: 3

      Pipeline:
        DepthBookMaintainer:
          LevelsCap: 200

        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sin-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: "23:00:00"
