apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: position-service-canary
  labels:
    release: prom-stack  # this label is required for prometheus autodiscovery of PodMonitor objects
spec:
  selector:
    matchLabels:
      prometheus-pod-scrape: enabled
      app: position-service-canary
  jobLabel: position-service-canary-stats
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: prometheus-port
      path: /metrics
      interval: 60s
      relabelings:
        - action: labelmap
          regex: "__meta_kubernetes_pod_label_(.+)"
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: pod_name
