apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bitbank-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-bitbank:2024.1.10.10-c375899
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1200m
  memory_request: 1000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 200
      ExchangeName: BitBank
      Monitor:
        DefaultConnectionCount: 2
        Symbols:
          - Name: BTC/JPY
          - Name: ETH/JPY
          - Name: QTUM/JPY
          - Name: BAT/JPY
          - Name: OMG/JPY
          - Name: BOBA/JPY
          - Name: XRP/JPY
          - Name: LTC/JPY
          - Name: MONA/JPY
          - Name: XLM/JPY
          - Name: XYM/JPY
          - Name: BCH/JPY
          - Name: DOT/JPY
          - Name: DOGE/JPY
          - Name: LINK/JPY
          - Name: ENJ/JPY
          - Name: ASTR/JPY
          - Name: AVAX/JPY
          - Name: AXS/JPY
          - Name: SAND/JPY
          - Name: FLR/JPY
          - Name: APE/JPY
          - Name: GALA/JPY
          - Name: CHZ/JPY
          - Name: MKR/JPY
          - Name: OAS/JPY
          - Name: GRT/JPY
          - Name: BNB/JPY
          - Name: ADA/JPY
          - Name: RNDR/JPY
          - Name: OP/JPY
          - Name: ARB/JPY
          - Name: POL/JPY

      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Publisher:
          V3BinaryFormat:
            DevelopmentMode: false
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
    PerfCollector:
      Enabled: false
