apiVersion: v1
kind: Service
metadata:
  name: dg-sin-01
  labels:
    app: dg-sin-01
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=Production
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/load-balancer-source-ranges:  '10.0.0.0/8,172.24.0.0/16'
    service.beta.kubernetes.io/aws-load-balancer-name: dg-sin-01
spec:
  type: LoadBalancer
  selector:
    app: dg-proxy
  ports:
    - name: dg-in
      protocol: TCP
      port: 11800
      targetPort: 11800
    - name: dg-out
      protocol: TCP
      port: 11900
      targetPort: 11900