---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: alc-risk-canary
  namespace: alc-risk-canary
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: alc-risk-canary-sa
