apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: canary-price-server
  labels:
    release: prom-stack  # this label is required for prometheus autodiscovery of PodMonitor objects
spec:
  selector:
    matchLabels:
      app: canary-price-server
  podMetricsEndpoints:
    - port: health-port
      path: /metrics
      interval: 30s
