apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: &devMode false
      ZmqTransport:
        Endpoint:
          - ">tcp://dg-proxy.dg-sel-01:11900"
    DataRecorder:
      S3Options:
        Bucket: "qs-bin-v2-sel"
      Redis:
        Host: elasticache-trading-platform-sel.aecacf.ng.0001.apn2.cache.amazonaws.com
      StreamOptions:
        DevelopmentMode: *devMode
              
kind: ConfigMap
metadata:
  name: data-recorder-config
