apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-mexc-207
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-mexc-v3:2024.3.25.105-fcfa5f6
  replicas: 1
  destiny: dg-rt
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    PriceServerClient:
      Address: ">tcp://qs-hk.node.al:10951,>tcp://qs-hk.node.al:10956,>tcp://qs-hk-1.node.al:10951,>tcp://qs-hk-2.node.al:10951"
    QuoteServer:
      ShardId: 206
      ExchangeName: Mexc
      Monitor:
        MaxSymbolsPerConnection: 10
        Symbols:
        - Name: POPCAT/USDT
        - Name: PRCL/USDT
        - Name: PRQ/USDT
        - Name: PUFFER/USDT
        - Name: PYTH/USDT
        - Name: QI/USDT
        - Name: RARI/USDT
        - Name: RATS/USDT
        - Name: RAY/USDC
        - Name: RDNT/USDT
        - Name: REEF/USDT
        - Name: RIF/USDT
        - Name: RLC/USDT
        - Name: RON/USDT
        - Name: ROOT/USDT
        - Name: RPL/USDT
        - Name: RSS3/USDT
        - Name: SAFE/USDT
        - Name: SC/USDT
        - Name: SCA/USDT
        - Name: SCRT/USDT
        DefaultConnectionCount: 2
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-hkg-03:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
