apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-backpack-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-backpack:2024.2.21.74-5fd8706
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: Backpack

      Monitor:
        Symbols:
          - Name: PYTH/USDC
          - Name: SOL/USDC
          - Name: JTO/USDC
          - Name: HNT/USDC
          - Name: USDT/USDC
          - Name: BONK/USDC
          - Name: JUP/USDC
          - Name: MOBILE/USDC
          - Name: WIF/USDC
          - Name: WEN/USDC
          - Name: BTC/USDC
          - Name: W/USDC
          - Name: RNDR/USDC
          - Name: PRCL/USDC
          - Name: SHFL/USDC
          - Name: HLG/USDC
          - Name: MON/USDC
          - Name: ZKJ/USDC
          - Name: UNA/USDC

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"

          V3BinaryFormat:
            DevelopmentMode: false
