apiVersion: apps/v1
kind: Deployment
metadata:
  name: qs-okcoinjp-202
spec:
  selector:
    matchLabels:
      app: qs-okcoinjp-202
  replicas: 1
  template:
    metadata:
      labels:
        app: qs-okcoinjp-202
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: qs
        image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-okcoinjp:2024.9.23.334-e46f633
        args:
        - "--config-files=/etc/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: security-master
          mountPath: /etc/security_master
        resources:
          limits:
            memory: 3500Mi
            cpu: 2000m
          requests:
            memory: 1048Mi
            cpu: 1100m
        ports:
        - name: health-port
          containerPort: 5001
        livenessProbe:
          tcpSocket:
            port: health-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: health-port
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6
        env:
        - name: TRIGGER_QS_RESTART_ENVVAR
          value: '1'
      imagePullSecrets:
      - name: ghcr-creds
      volumes:
      - name: config-volume
        configMap:
          name: qs-okcoinjp-202-config
      - name: security-master
        hostPath:
          path: /synced_files
      tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
      nodeSelector:
        node/destiny: dg-rt-az4
