apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: &devMode false
      ZmqTransport:
        Endpoint:
          - ">tcp://dg-proxy.dg-collect:11900"
    DataRecorder:
      S3Options:
        Bucket: "qs-bin-v2-tyo"
      Redis:
        Host: elasticache-trading-platform-tyo.qcgrcw.ng.0001.apne1.cache.amazonaws.com
      StreamOptions:
        DevelopmentMode: false

kind: ConfigMap
metadata:
  name: data-recorder-config
