apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bithumb-202
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-bithumb:2023.3.15.43-2d9612652a4ab69b61171294fd51ed474144c9d1
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 201
      ExchangeName: Bithumb
      CheckStaleMarketDataTrigger:
        Interval: 00:00:01

      Monitor:
        DefaultConnectionCount: 3
        Symbols:
          - Name: ETC/KRW
          - Name: AQT/KRW
          - Name: RLY/KRW
          - Name: XVS/KRW
          - Name: WIKEN/KRW
          - Name: NMR/KRW
          - Name: XRP/KRW
          - Name: LRC/KRW
          - Name: ELF/KRW
          - Name: UNI/KRW
          - Name: ARB/KRW
          - Name: DVI/KRW
          - Name: FX/KRW
          - Name: ACH/KRW
          - Name: AERGO/KRW
          - Name: ALICE/KRW
          - Name: FANC/KRW
          - Name: LM/KRW
          - Name: RSS3/KRW
          - Name: OAS/KRW
          - Name: WLD/KRW
          - Name: HFT/KRW
          - Name: RPL/KRW
          - Name: ID/KRW
          - Name: BIGTIME/KRW
          - Name: ALEX/KRW
          - Name: HIGH/KRW
          - Name: ARKM/KRW
          - Name: FET/KRW
          - Name: STAT/KRW
          - Name: ZTX/KRW
          - Name: MINA/KRW
          - Name: IOTX/KRW
          - Name: HIFI/KRW
          - Name: STORJ/KRW
      RateLimiter:
        Http:
          UsageLimit: 1000
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.01
          RequestCosts:
            Snapshot: 10

      Pipeline:
        AbArbitrator:
          DepthBookProcessing:
            OrderBy: Timestamp
            Deduplicate: false
            IncludeInHash: Timestamp
          TradesProcessing:
            OrderBy: Timestamp
            Deduplicate: true
            IncludeInHash: Timestamp

        DepthBookMaintainer:
          LevelsCap: 30
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 00:01:00
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sel-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
