apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-zeta-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-zeta:2024.3.12.83-9c719ac
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: Zeta

      Monitor:
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: ETH/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: BTC/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: SOL/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: JUP/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: TIA/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: ARB/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: PYTH/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: APT/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: STRK/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: SEI/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: JTO/USDC
              NamePatterns:
                - '_Perpetual'
      Pipeline:
        AbArbitrator:
          DepthBookProcessing:
            OrderBy: Timestamp
          TradesProcessing:
            OrderBy: Timestamp
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"

          V3BinaryFormat:
            DevelopmentMode: false
