apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-mexc-215
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-mexc-v3:2024.3.28.108-3ce6dd0
  replicas: 0
  destiny: dg-rt
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    PriceServerClient:
      Address: ">tcp://qs-hk.node.al:10951,>tcp://qs-hk.node.al:10956,>tcp://qs-hk-1.node.al:10951,>tcp://qs-hk-2.node.al:10951"
    QuoteServer:
      ShardId: 214
      ExchangeName: Mexc
      Monitor:
        MaxSymbolsPerConnection: 10
        Symbols:
          - Name: RON/USDT
          - Name: STARL/USDT
          - Name: SUIP/USDT
          - Name: UNIBOT/USDT
          - Name: SOULS/USDT
          - Name: MLT/USDT
          - Name: CTXC/USDT
          - Name: YFI/USDT
          - Name: TIN/USDT
          - Name: EJS/USDT
          - Name: MCHC/USDT
          - Name: OZONE/USDT
          - Name: NPT/USDT
          - Name: NUM/USDT
          - Name: SCRT/USDT
          - Name: TKX/USDT
          - Name: PONKE/USDT
          - Name: MBD/USDT
          - Name: ACE/USDT
          - Name: SNS/USDT
          - Name: RIF/USDT
          - Name: DUSK/USDT
          - Name: PTH/USDT
          - Name: UFT/USDT
          - Name: SAVM/USDT
          - Name: MANTA/USDT
          - Name: ONDO/USDT
          - Name: FUD/USDT
          - Name: BERRY/USDT
          - Name: TROLL/USDT
          - Name: POKT/USDT
          - Name: ZUZALU/USDT
          - Name: RITE/USDT
        DefaultConnectionCount: 2
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-hkg-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
