apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-mexc-216
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-mexc-v3:2024.3.28.108-3ce6dd0
  replicas: 0
  destiny: dg-rt
  cpu_request: 1000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    PriceServerClient:
      Address: ">tcp://qs-hk.node.al:10951,>tcp://qs-hk.node.al:10956,>tcp://qs-hk-1.node.al:10951,>tcp://qs-hk-2.node.al:10951"
    QuoteServer:
      ShardId: 215
      ExchangeName: Mexc
      Monitor:
        MaxSymbolsPerConnection: 10
        Symbols:
          - Name: MBOX/USDT
          - Name: PROPS/USDT
          - Name: DAG/USDT
          - Name: TRADE/USDT
          - Name: OBI/USDT
          - Name: SOL/USDC
          - Name: FITFI/USDT
          - Name: PROPC/USDT
          - Name: NXRA/USDT
          - Name: TSUKA/USDT
          - Name: FACTR/USDT
          - Name: VC/USDT
          - Name: POLS/USDT
          - Name: BNX/USDT
          - Name: MYST/USDT
          - Name: XRP/USDC
          - Name: NBS/USDT
          - Name: GLQ/USDT
          - Name: MNTL/USDT
          - Name: UBXS/USDT
          - Name: NABOX/USDT
          - Name: SKL/USDT
          - Name: LITHO/USDT
          - Name: LUNCH/USDT
          - Name: LOOP/USDT
          - Name: CAPO/USDT
          - Name: PNG/USDT

        DefaultConnectionCount: 2
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-hkg-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
