apiVersion: apps/v1
kind: Deployment
metadata:
  name: fees-editor
spec:
  selector:
    matchLabels:
      app: fees-editor
  replicas: 1
  template:
    metadata:
      labels:
        app: fees-editor
    spec:
      serviceAccountName: ui-apps-sa-prod
      containers:
        - name: fees-editor
          image: ghcr.io/alphalab-hq/fees-editor:1.1.2
          resources:
            requests:
              cpu: "100m"
              memory: 100Mi
            limits:
              cpu: "500m"
              memory: 500Mi
          env:
            - name: API_PORT
              value: "1234"
            - name: NODE_ENV
              value: production
            - name: LOGIN_REDIRECT_LOCATION
              value: https://tools.alphalab.cc/fees-editor
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: mysql-host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: mysql-port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: mysql-database
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: coin-manager-secrets
                  key: redis-host
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: google-client-secret
            - name: COOKIE_ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fees-editor-secrets
                  key: coockie-encryption

          ports:
            - containerPort: 1234
      tolerations:
        - key: node/destiny
          operator: 'Equal'
          value: 'alc-ui'
          effect: 'NoSchedule'
      nodeSelector:
        node/destiny: alc-ui
      imagePullSecrets:
        - name: ghcr-creds
