apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-binance-209
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-binance:2024.12.2.127-6a165c5
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1500m
  memory_request: 1000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 208
      ExchangeName: Binance
      Binance:
        Variant: DeltaSimplified
        DedupTradesEarly: true
        DedupTickersEarly: true

      Monitor:
        DefaultConnectionCount: 3
        Symbols:
          - Name: TRX/EUR
          - Name: FLOW/BTC
          - Name: FLOW/USDT
          - Name: QNT/USDT
          - Name: CLV/USDT
          - Name: PERP/BTC
          - Name: QNT/BTC
          - Name: WAN/USDT
          - Name: RAY/USDT
          - Name: ALPACA/USDT
          - Name: MINA/USDT
          - Name: FARM/USDT
          - Name: QUICKSWAP/USDT
          - Name: CLV/BTC
          - Name: AR/BTC
          - Name: MINA/BTC
          - Name: MBOX/USDT
          - Name: REQ/USDT
          - Name: SYS/BTC
          - Name: GHST/USDT
          - Name: MBOX/BTC
          - Name: WAXP/USDT
          - Name: WAXP/BTC
          - Name: DAR/USDT
          - Name: SSV/BTC
          - Name: SSV/ETH
          - Name: CHESS/USDT
          - Name: LOKA/USDT
          - Name: API3/USDT
          - Name: SCRT/USDT
          - Name: API3/BTC
          - Name: CYBER/USDT
          - Name: BLZ/BTC
          - Name: CYBER/BTC
          - Name: BADGER/USDT
          - Name: SEI/BNB
          - Name: WLD/BTC
          - Name: NMR/BTC
          - Name: CYBER/BNB
          - Name: PROM/USDT
          - Name: ARK/USDT
          - Name: FTT/USDT
          - Name: GFT/USDT
          - Name: CREAM/USDT
          - Name: BLUR/USDT
          - Name: VIC/USDT
          - Name: PIVX/USDT
          - Name: GTC/BTC
          - Name: PYTH/USDT
          - Name: PYTH/BTC
          - Name: FIL/USDT
          - Name: PHB/USDT
          - Name: HOOK/USDT
          - Name: HFT/USDT
          - Name: ASR/TRY
          - Name: ATM/TRY
          - Name: ACM/TRY
          - Name: BAR/TRY
          - Name: JUV/TRY
          - Name: PSG/TRY
          - Name: BTC/FDUSD
          - Name: ETH/FDUSD

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
