apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-binance-212
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-binance:2024.12.2.127-6a165c5
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1500m
  memory_request: 1000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 211
      ExchangeName: Binance
      Binance:
        Variant: DeltaSimplified
        DedupTradesEarly: true
        DedupTickersEarly: true

      Monitor:
        DefaultConnectionCount: 3
        Symbols:
          - Name: MANA/USDT
          - Name: MANA/BTC
          - Name: STORJ/USDT
          - Name: STORJ/BTC
          - Name: DATA/USDT
          - Name: DATA/BTC
          - Name: DODO/USDT
          - Name: DODO/BTC
          - Name: COTI/BTC
          - Name: OGN/USDT
          - Name: OGN/BTC
          - Name: TLM/USDT
          - Name: MAGIC/USDT
          - Name: HFT/BTC
          - Name: APT/EUR
          - Name: USDC/USDT
          - Name: BTC/USDC
          - Name: BNT/USDT
          - Name: DENT/USDT
          - Name: VET/BNB
          - Name: ADA/EUR
          - Name: ADX/BTC
          - Name: CHZ/USDT
          - Name: DCR/USDT
          - Name: ETH/BTC
          - Name: BCH/BTC
          - Name: XLM/USDT
          - Name: KNC/BTC
          - Name: AXS/BTC
          - Name: AXS/BNB
          - Name: EOS/BTC
          - Name: BCH/USDT
          - Name: QTUM/BTC
          - Name: QTUM/USDT
          - Name: XTZ/USDT
          - Name: XTZ/BTC
          - Name: BNB/USDT
          - Name: TRU/USDT
          - Name: TRU/BTC
          - Name: GRT/EUR
          - Name: STMX/USDT
          - Name: SUI/BNB
          - Name: BTC/JPY
          - Name: ETH/JPY
          - Name: BNB/JPY
      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false