apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: &devMode true
      ZmqTransport:
        Endpoint:
          - ">tcp://dg-proxy.dg-test:11900"
          - ">tcp://colo-cldn-tokyo-test-01.node.al:19990"
          - ">tcp://colo-cldn-tokyo-test-01.node.al:19991"
    DataRecorder:
      S3Options:
        Bucket: "qs-bin-v2-tyo"
      Redis:
        Host: elasticache-trading-platform-tyo.qcgrcw.ng.0001.apne1.cache.amazonaws.com
      StreamOptions:
        DevelopmentMode: true

kind: ConfigMap
metadata:
  name: data-recorder-config
