apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-binance-delta-pipeline-notickers
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-binance:2024.10.31.121-128fbed
  replicas: 0
  destiny: dg-test
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 116
      ExchangeName: Binance
      Binance:
        Variant: DeltaSimplified
        DedupTradesEarly: true
        DedupTickersEarly: false
      Monitor:
        DefaultConnectionCount: 3
        Symbols:
          - Name: CVP/USDT
          - Name: POWR/USDT
          - Name: FRONT/USDT
          - Name: PEPE/TRY
          - Name: FLOKI/USDT
          - Name: GLM/USDT
          - Name: MAV/USDT
          - Name: GAS/USDT
          - Name: BTC/USDT
          - Name: ETH/USDT
   
      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-test:11800"

          V3BinaryFormat:
            DevelopmentMode: true

