apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-deribitoptions-111
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-deribit:2024.12.17.75-b3f7dd2
  replicas: 1
  destiny: dg-nrt
  cpu_request: 1100m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 110
      ExchangeName: DeribitOptions

      DeribitOptions:
        ExchangeConnection:
          OrderBookUpdateChannel:
            DebugVerbosity: 2
          TradeChannel:
            DebugVerbosity: 2
          ParsingOptions:
            FastParsing: false # true for fast parsing, false will use fallback (JsonDispatcher) mechanism
          Sync:
            Interval: 0 # ms 0 - disable
        SnapshotMakerStrategy:
          DebugVerbosity: 2

      PeriodicSnapshotTrigger:
        Enabled: true
        MinPeriodSeconds: 30
        MaxPeriodSeconds: 60
      
      RateLimiter:
        Http:
          UsageLimit: 40
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.50
          RequestCosts:
            Snapshot: 20
      Monitor:
        DefaultConnectionCount: 1
        MaxSymbolsPerConnection: 100
        DerivedSymbols:
          Type: Options
          Symbols:
            - UnderlyingName: BTC/USD
              NamePatterns:
                - 'BTC/USD_P.*DeribitOptions'
        #Symbols:  
        #  - Name: MATIC/USDC_C_0.52_20240830@DeribitOptions
        #  - Name: MATIC/USDC_C_0.54_20240830@DeribitOptions
        #  - Name: MATIC/USDC_C_0.55_20240830@DeribitOptions
        #  - Name: MATIC/USDC_P_0.52_20240830@DeribitOptions
        #  - Name: MATIC/USDC_P_0.54_20240830@DeribitOptions
        #  - Name: MATIC/USDC_P_0.55_20240830@DeribitOptions


      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-test:11800"
          V3BinaryFormat:
            DevelopmentMode: true
        DepthBookMaintainer:
          TickersNeedExchangeTime: true

# deribitoptions.prop.yaml
