apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-binancefut-208
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-binance:2024.8.27.97-d474169
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    QuoteServer:
      ShardId: 207
      ExchangeName: BinanceFut


      Monitor:
        DefaultConnectionCount: 1
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: XEM/USDT
            - UnderlyingName: ALICE/USDT
            - UnderlyingName: CHR/USDT
            - UnderlyingName: MANA/USDT
            - UnderlyingName: HBAR/USDT
            - UnderlyingName: DENT/USDT
            - UnderlyingName: STMX/USDT
            - UnderlyingName: LINA/USDT
            - UnderlyingName: MTL/USDT
            - UnderlyingName: CELO/USDT
            - UnderlyingName: AUCTION/USDT
            - UnderlyingName: BADGER/USDT
            - UnderlyingName: KAS/USDT
            - UnderlyingName: SUPER/USDT
            - UnderlyingName: ONG/USDT
            - UnderlyingName: USTC/USDT
            - UnderlyingName: XEC/USDT
            - UnderlyingName: NFP/USDT
            - UnderlyingName: AXL/USDT
            - UnderlyingName: IO/USDT

      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: "00:00:01"
          PriceForChangeThreshold: 3.0e-5
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-02:11800"

          V3BinaryFormat:
            DevelopmentMode: false

