apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: &devMode false
      ZmqTransport:
        Endpoint:
          - ">tcp://dg-proxy.dg-fra-01:11900"
        #Monitor: false
        #MonitorTimeoutMS: 100
    DataRecorder:
      S3Options:
        Bucket: "qs-bin-v2-fra"
      Redis:
        Host: elasticache-trading-platform-fra.pz5c7g.ng.0001.euc1.cache.amazonaws.com
      StreamOptions:
        DevelopmentMode: *devMode

kind: ConfigMap
metadata:
  name: data-recorder-config
