apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-okex-226
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-okex:2024.2.8.19-b35840e
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 225
      ExchangeName: OKEx
      OKEx:
        L2UpdateChannel: books
        Passphrase: "shfjk#54JS3djDJ"
        ApiKey: "5b10705f-b0e4-45ce-aa65-1e8bb93878c8"
        Secret: "E7AA910F4291AF4769FC4013BDC1FC94"
      Monitor:
        Symbols:
          - Name: DOGE/USDT
          - Name: OKB/USDT
          - Name: SOL/BTC
          - Name: SOL/USDT
          - Name: STORJ/USDT
          - Name: KLAY/USDT
          - Name: WOO/USDT
          - Name: ASTR/USDT
          - Name: KDA/USDT
          - Name: GAS/USDT
          - Name: RVN/USDT
          - Name: ALPHA/USDT
          - Name: GLM/USDT
          - Name: CELR/USDT
          - Name: NULS/USDT
          - Name: SHIB/USDT
          - Name: LAT/USDT
          - Name: GALA/USDT
          - Name: WCFG/USDT
          - Name: NEAR/USDT
          - Name: CTXC/USDT
          - Name: MDT/USDT
          - Name: RADAR/USDT
          - Name: FET/USDT
          - Name: LAMB/USDT
          - Name: JUP/USDT
          - Name: ZETA/USDT


      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-hkg-02:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
