apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-okex-225
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-okex:2024.2.8.19-b35840e
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 224
      ExchangeName: OKEx
      OKEx:
        L2UpdateChannel: books
        Passphrase: "shfjk#54JS3djDJ"
        ApiKey: "5b10705f-b0e4-45ce-aa65-1e8bb93878c8"
        Secret: "E7AA910F4291AF4769FC4013BDC1FC94"
      Monitor:
        Symbols:
          - Name: AAVE/USDT
          - Name: BAT/USDT
          - Name: SAND/USDT
          - Name: OKT/USDT
          - Name: BETH/ETH
          - Name: BETH/USDT
          - Name: CVC/USDT
          - Name: MANA/USDT
          - Name: CTC/USDT
          - Name: GRT/USDT
          - Name: ONEINCH/USDT
          - Name: ZIL/USDT
          - Name: IOTA/USDT
          - Name: ORBS/USDT
          - Name: EGLD/USDT
          - Name: EOS/USDC
          - Name: VELO/USDT
          - Name: DYDX/USDT
          - Name: ETH/USDC
          - Name: VELODROME/USDT
          - Name: ID/USDT
          - Name: BONE/USDT
          - Name: SUI/USDT
          - Name: GLMR/USDT
          - Name: LOOKS/USDT
          - Name: RSS3/USDT


      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-hkg-02:11800"
          V3BinaryFormat:
            DevelopmentMode: false
