apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: false

      Workflow:
        Type: SplitBySymbolCount
        SymbolsCount: 600
        InitialWorkflowCount: 4
    
      ZmqTransport:
        DefaultEndpointName: "default"
        Endpoint:
          default:
            - ">tcp://dg-proxy.dg-hkg-01:11900"
            - ">tcp://dg-proxy.dg-hkg-03:11900"
        LocalByteCacheSize: 65536
        ReceiveHighWatermark: 300000
        
      Extension: InstanceId
      Subscription: NonSubSampled
      ExtensionDeserializationErrorHandling: None

    Subscription:
      Prefix: ""
      ExporterName: "qs-exporter-hongkong-csharp-2"
      Exchanges:
        default:
          - "OKExFut"

    MetricConfigurationProvider:
      DefaultEnabled: true
      Rules:
        - Metric: "al_qs_book_agg_amt_from_mid"
          Enabled: false
        - Metric: "al_qs_prc_for_usd_amt"
          Enabled: false
      

kind: ConfigMap
metadata:
  name: qs-exporter-config-csharp-2
