QuoteServers:
  - name: qs-hyperliquid-201
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-hyperliquid:2024.3.15.91-3f08305
    requests:
      cpu: 1100m
      memory: 4000Mi
    limits:
      cpu: 2000m
      memory: 4000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
        FileLoader:
          DisableNotificationsService: true

      QuoteServer:
        ShardId: 200
        ExchangeName: Hyperliquid

        Monitor:
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: BTC/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: ETH/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: SOL/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: TIA/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: AVAX/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: OP/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: ARB/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: LDO/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: SUI/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: BLUR/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: MKR/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: SEI/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: ORDI/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: WLD/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: BLAST/USDT
                NamePatterns:
                  - '_Perpetual'
              - UnderlyingName: PYTH/USDT
                NamePatterns:
                  - '_Perpetual'
          DefaultConnectionCount: 3

        Pipeline:
          AbArbitrator:
            DepthBookProcessing:
              OrderBy: Timestamp
            TradesProcessing:
              OrderBy: Timestamp
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
            V3BinaryFormat:
              DevelopmentMode: false
