apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-aevo-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-aevo:2024.4.16.127-70ab427
  replicas: 0
  destiny: dg-rt-az4
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: Aevo

      Monitor:
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: ETH/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: BTC/USDC
              NamePatterns:
                - '_Perpetual'
        DefaultConnectionCount: 3

      Pipeline:
        AbArbitrator:
          DepthBookProcessing:
            OrderBy: Timestamp
          TradesProcessing:
            OrderBy: Timestamp
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
          V3BinaryFormat:
            DevelopmentMode: false
