apiVersion: apps/v1
kind: Deployment
metadata:
  name: signer-config
spec:
  selector:
    matchLabels:
      app: signer-config
  replicas: 1
  template:
    metadata:
      labels:
        app: signer-config
    spec:
      containers:
        - name: signer-config
          image: ghcr.io/alphalab-hq/signer-config:1.1.0
          resources:
            requests:
              cpu: "250m"
              memory: 200Mi
            limits:
              cpu: "500m"
              memory: 500Mi
          env:
            - name: API_PORT
              value: "4000"
            - name: NODE_ENV
              value: production
            - name: LOGIN_REDIRECT_LOCATION
              value: https://tools.alphalab.cc/signer-config
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: mysql-host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: mysql-port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: mysql-database
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: google-client-secret
            - name: COOKIE_ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: cookie-encryption
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: signer-config-secrets
                  key: redis-host
          ports:
            - containerPort: 4000
      tolerations:
        - key: node/destiny
          operator: 'Equal'
          value: 'alc-ui'
          effect: 'NoSchedule'
      nodeSelector:
        node/destiny: alc-ui  
      imagePullSecrets:
        - name: ghcr-creds
