apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ui-apps-signer-config-ext-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ui-apps
    kind: SecretStore
  target:
    name: signer-config-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: tool/prod/signer-config
