apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-dydxv4-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-dydxv4:2024.1.19.58-c1ea6f0
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 1200m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: dYdXV4

      Monitor:
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: ETH/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: BTC/USDC
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: SOL/USDC
              NamePatterns:
                - '_Perpetual'
      Pipeline:
        AbArbitrator:
          DepthBookProcessing:
            OrderBy: Timestamp
          TradesProcessing:
            OrderBy: Timestamp
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-06:11800"

          V3BinaryFormat:
            DevelopmentMode: false
