apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bybitspot-205
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-bybit:2024.1.10.8-c375899
  replicas: 1
  destiny: dg-rt
  cpu_request: 1100m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    QuoteServer:
      ShardId: 204
      ExchangeName: BybitSpot
      Monitor:
        Symbols:
          - Name: MBOX/USDT
          - Name: BOBA/USDT
          - Name: GLMR/USDT
          - Name: PERP/USDT
          - Name: MASK/USDT
          - Name: ROOT/USDT
          - Name: MOVR/USDT
          - Name: CAKE/USDT
          - Name: KSM/USDT
          - Name: C98/USDT
          - Name: USTC/USDT
          - Name: ETHW/USDT
          - Name: ALGO/USDT
          - Name: SOL/BTC
          - Name: NEAR/USDT
          - Name: AVAX/USDC
          - Name: ZRX/USDT
          - Name: RUNE/USDT
          - Name: TIA/USDT
          - Name: YFI/USDT
          - Name: MEME/USDT
          - Name: ORDI/USDT
          - Name: KAS/USDT
          - Name: TOKEN/USDT
          - Name: PEOPLE/USDT
          - Name: ENS/USDT
          - Name: SSV/USDT
          - Name: XAI/USDT
          - Name: ZKF/USDT
          - Name: AGLD/USDT
          - Name: FXS/USDT
          - Name: THETA/USDT
          - Name: LDO/USDC
          - Name: CPOOL/USDT
          - Name: CELO/USDT
          - Name: ONE/USDT
        DefaultConnectionCount: 2
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        DepthBookMaintainer:
          LevelsCap: 50
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sin-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
