apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bybitspot-203
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-bybit:2024.1.10.8-c375899
  replicas: 1
  destiny: dg-rt
  cpu_request: 1100m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    QuoteServer:
      ShardId: 202
      ExchangeName: BybitSpot
      Monitor:
        Symbols:
          - Name: LADYS/USDT
          - Name: ARB/USDT
          - Name: TOMI/USDT
          - Name: OP/USDT
          - Name: SOL/USDC
          - Name: APEX/USDT
          - Name: DYDX/USDT
          - Name: LDO/USDT
          - Name: VINU/USDT
          - Name: TRX/USDT
          - Name: ARB/USDC
          - Name: HFT/USDT
          - Name: PEPE/USDT
          - Name: FB/USDT
          - Name: ETH/BTC
          - Name: BNB/USDT
          - Name: MAGIC/USDT
          - Name: BLUR/USDT
          - Name: WAXL/USDT
          - Name: UNI/USDT
          - Name: SUI/USDC
          - Name: LINK/USDT
          - Name: BTC/USDC
          - Name: GRT/USDT
          - Name: FIL/USDT
          - Name: STETH/USDT
          - Name: FTT/USDT
          - Name: USDE/USDT
          - Name: DEGEN/USDT
          - Name: BRETT/USDT
          - Name: NOT/USDT
          - Name: TAIKO/USDT
          - Name: WIF/USDT
          - Name: MON/USDT
          - Name: ENA/USDT
          - Name: BB/USDT
          - Name: CEL/USDT
          - Name: W/USDT
          - Name: ETHFI/USDT
          - Name: BOME/USDT
          - Name: MERL/USDT
          - Name: NYAN/USDT
          - Name: NIBI/USDT


        DefaultConnectionCount: 2
      Pipeline:
        Disruptor:
          DisruptorStatsDecoratorEnabled: false
        DepthBookMaintainer:
          LevelsCap: 50
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sin-01:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      Enabled: false
