apiVersion: apps/v1
kind: Deployment
metadata:
  name: alc-funding-rate-broadcaster
spec:
  selector:
    matchLabels:
      app: alc-funding-rate-broadcaster
  replicas: 1
  template:
    metadata:
      labels:
        app: alc-funding-rate-broadcaster
    spec:
      terminationGracePeriodSeconds: 25
      containers:
      - name: alc-funding-rate-broadcaster
        image: ghcr.io/alphalab-hq/alc-fundingrate-broadcaster:2025.1.7.43-4006e00609d0abfab7db43b883da1e8b14e224e5
        args:
        - "--configs=/etc/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: security-master
          mountPath: /etc/security_master
        resources:
          limits:
            memory: 3500Mi
            cpu: 1500m
          requests:
            memory: 2048Mi
            cpu: 1000m
        ports:
        - name: health-port
          containerPort: 5000
        - name: pub-port
          containerPort: 5001
        - name: sub-port
          containerPort: 5002
        livenessProbe:
          tcpSocket:
            port: health-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: health-port
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6
      imagePullSecrets:
      - name: ghcr-creds
      volumes:
      - name: config-volume
        configMap:
          name: alc-funding-rate-broadcaster-config
      - name: security-master
        hostPath:
          path: /synced_files/all
      tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-nrt
        effect: NoSchedule
      nodeSelector:
        node/destiny: dg-nrt
