apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-backpackfut-test
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-backpack:2025.1.8.392-d08a17c
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 200
      ExchangeName: BackpackFut
      Monitor:
        Symbols:
          - Name: BTC/USDC_Perpetual@BackpackFut
          - Name: SOL/USDC_Perpetual@BackpackFut
          - Name: ETH/USDC_Perpetual@BackpackFut
      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-07:11800"
          V3BinaryFormat:
            DevelopmentMode: false
