apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: false

      ZmqTransport:
        Endpoint: 
          - ">tcp://dg-proxy.dg-collect:11900"
      Extension: InstanceId
      ExtensionDeserializationErrorHandling: None

    Publication:
      ShardId: 44
      DevelopmentMode: false

      ZmqTransport:
        Endpoint: ">tcp://dg-proxy.dg-tokyo-06:11800"

kind: ConfigMap
metadata:
  name: l1-generator-config
