apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-upbit-204
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-upbit:2023.5.29.28-6735d512272cc866c0a7c6947030ef0f269ac912
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 203
      ExchangeName: Upbit

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 12

        Symbols:
          - Name: XRP/KRW
          - Name: QTUM/KRW
          - Name: ZIL/KRW
          - Name: TRX/KRW
          - Name: MLK/KRW
          - Name: MED/KRW
          - Name: DOGE/KRW
          - Name: STMX/KRW
          - Name: WAXP/KRW
          - Name: BAT/KRW
          - Name: STEEM/KRW
          - Name: NEO/KRW
          - Name: VET/KRW
          - Name: WAVES/KRW
          - Name: QKC/KRW
          - Name: THETA/KRW
          - Name: TFUEL/KRW
          - Name: HBAR/KRW
          - Name: ANKR/KRW
          - Name: LOOM/KRW
          - Name: LINK/KRW
          - Name: AQT/KRW
          - Name: ASTR/KRW
          - Name: UXLINK/KRW
          - Name: BIGTIME/KRW
          - Name: CARV/KRW
          - Name: SAFE/KRW
          - Name: W/KRW
          - Name: DRIFT/KRW
          - Name: GAME2/KRW

      Pipeline:
        DepthBookMaintainer:
          LevelsCap: 15

        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-sel-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
