apiVersion: v1
data:
  config.yaml: |-
    QsClient:
      DevelopmentMode: false
    
      ZmqTransport:
        Endpoint: 
          - ">tcp://dg-proxy.dg-hkg-03:11900"
      Extension: InstanceId
      ExtensionDeserializationErrorHandling: None
    
    Publication:
      ShardId: 4
      DevelopmentMode: false

      ZmqTransport:
        Endpoint: ">tcp://dg-proxy.dg-hkg-03:11800"

kind: ConfigMap
metadata:
  name: l1-generator-config
