apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoinfut-208
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    QuoteServer:
      ShardId: 207
      ExchangeName: KuCoinFut
      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 10
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: BEL/USDT
            - UnderlyingName: KEY/USDT
            - UnderlyingName: EDU/USDT
            - UnderlyingName: TRU/USDT
            - UnderlyingName: MTL/USDT
            - UnderlyingName: RDNT/USDT
            - UnderlyingName: AAVE/USDT
            - UnderlyingName: ACH/USDT
            - UnderlyingName: ID/USDT
            - UnderlyingName: SNX/USDT
            - UnderlyingName: CELR/USDT
            - UnderlyingName: CELO/USDT
            - UnderlyingName: SFP/USDT
            - UnderlyingName: UNFI/USDT
            - UnderlyingName: TRB/USDT
            - UnderlyingName: BAKE/USDT
            - UnderlyingName: POLYX/USDT
            - UnderlyingName: QTUM/USDT
            - UnderlyingName: ORBS/USDT
            - UnderlyingName: GAS/USDT
            - UnderlyingName: PEOPLE/USDT
            - UnderlyingName: REN/USDT
            - UnderlyingName: USTC/USDT
            - UnderlyingName: SUPER/USDT
            - UnderlyingName: XCN/USDT
            - UnderlyingName: JTO/USDT
            - UnderlyingName: NTRN/USDT
            - UnderlyingName: PYTH/USDT

      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
