apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoinfut-207
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.17.76-6cc293d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    QuoteServer:
      ShardId: 206
      ExchangeName: KuCoinFut
      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 10
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: SEI/USDT
            - UnderlyingName: OXT/USDT
            - UnderlyingName: MAGIC/USDT
            - UnderlyingName: ROSE/USDT
            - UnderlyingName: LQTY/USDT
            - UnderlyingName: ONT/USDT
            - UnderlyingName: OMG/USDT
            - UnderlyingName: MKR/USDT
            - UnderlyingName: STORJ/USDT
            - UnderlyingName: MAV/USDT
            - UnderlyingName: BAND/USDT
            - UnderlyingName: AUDIO/USDT
            - UnderlyingName: AGLD/USDT
            - UnderlyingName: COMBO/USDT
            - UnderlyingName: KDA/USDT
            - UnderlyingName: LEVER/USDT
            - UnderlyingName: GTC/USDT
            - UnderlyingName: KNC/USDT
            - UnderlyingName: TON/USDT
            - UnderlyingName: REEF/USDT
            - UnderlyingName: ARK/USDT
            - UnderlyingName: BNT/USDT
            - UnderlyingName: XTZ/USDT
            - UnderlyingName: CRO/USDT
            - UnderlyingName: BIGTIME/USDT
            - UnderlyingName: TOKEN/USDT
            - UnderlyingName: CAKE/USDT
            - UnderlyingName: WAXP/USDT
            - UnderlyingName: AR/USDT
            - UnderlyingName: TWT/USDT
            - UnderlyingName: PERP/USDT
            - UnderlyingName: CHZ/USDT

      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
