apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bitstamp-202
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-bitstamp:2023.1.16.26-295ca568dbcc2558ad15c52bd672a2daf1b01bf8
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 201

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 12
        Symbols:
          - Name: ETH/USD
          - Name: ETH/USDT
          - Name: USDT/USD
          - Name: USDT/EUR
          - Name: KNC/USD
          - Name: KNC/EUR
          - Name: DAI/USD
          - Name: USDC/USDT
          - Name: GRT/USD
          - Name: GRT/EUR
          - Name: ZRX/USD
          - Name: ZRX/EUR
          - Name: AAVE/BTC
          - Name: AAVE/EUR
          - Name: AAVE/USD
          - Name: SOL/USD
          - Name: SOL/EUR
          - Name: XRP/USD

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-fra-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
