apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bitstamp-204
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-bitstamp:2023.1.16.26-295ca568dbcc2558ad15c52bd672a2daf1b01bf8
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 203

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 10
        Symbols:
          - Name: YFI/USD
          - Name: YFI/EUR
          - Name: ALGO/USD
          - Name: ALGO/EUR
          - Name: MKR/USD
          - Name: MKR/EUR
          - Name: COMP/USD
          - Name: COMP/EUR
          - Name: BTC/USDT
          - Name: BTC/USDC
          - Name: XRP/GBP
          - Name: XLM/BTC
          - Name: BTC/USD
          - Name: BTC/GBP
          - Name: AXS/USD
          - Name: AXS/EUR
          - Name: ENJ/USD
          - Name: ENJ/EUR
          - Name: MATIC/EUR
          - Name: AUDIO/USD
          - Name: AUDIO/EUR
          - Name: AUDIO/BTC

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-fra-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
