apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bitstamp-203
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-bitstamp:2023.1.16.26-295ca568dbcc2558ad15c52bd672a2daf1b01bf8
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 202

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 10
        Symbols:
          - Name: CHZ/USD
          - Name: BTC/EUR
          - Name: LINK/GBP
          - Name: ADA/EUR
          - Name: ADA/USD
          - Name: SUSHI/USD
          - Name: SAND/EUR
          - Name: MATIC/USD
          - Name: SAND/USD
          - Name: CHZ/EUR
          - Name: ETH/USDC
          - Name: LTC/USD
          - Name: ETH/EUR
          - Name: BAT/EUR
          - Name: BAT/USD
          - Name: XRP/BTC
          - Name: XRP/EUR
          - Name: EUR/USD
          - Name: GBP/USD


      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-fra-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
