apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-bitstamp-201
spec:
  image: ghcr.io/alphalab-hq/alc-qs-exchange-bitstamp:2023.1.16.26-295ca568dbcc2558ad15c52bd672a2daf1b01bf8
  replicas: 1
  destiny: dg-rt
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 200

      Monitor:
        DefaultConnectionCount: 2
        MaxSymbolsPerConnection: 12
        Symbols:
          - Name: BCH/BTC
          - Name: BCH/USD
          - Name: LTC/BTC
          - Name: LTC/EUR
          - Name: ETH/BTC
          - Name: BCH/EUR
          - Name: SNX/USD
          - Name: SNX/EUR
          - Name: CRV/USD
          - Name: CRV/EUR
          - Name: LINK/USD
          - Name: LINK/EUR
          - Name: ETH/GBP
          - Name: XLM/USD
          - Name: XLM/EUR
          - Name: UNI/USD
          - Name: UNI/EUR
          - Name: UNI/BTC
          - Name: XRP/USDT
          - Name: USDC/USD
          - Name: USDC/EUR


      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-fra-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 01:00:00
