apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-injectivefut-201
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-injective:2024.11.16.389-bef10bc
  replicas: 1
  destiny: dg-rt
  cpu_request: 1000m
  memory_request: 1000Mi
  cpu_limit: 2000m
  memory_limit: 3000Mi
  config: |-
    
    # Serilog:
    #   MinimumLevel:
    #     Default: Verbose
    #     Override:
    #       Microsoft: Verbose
    #       Microsoft.Hosting.Lifetime: Verbose
    
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true

    QuoteServer:
      ShardId: 200
      ExchangeName: InjectiveFut
      Monitor:
        MaxSymbolsPerConnection: 1
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: BTC/USDT
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: ETH/USDT
              NamePatterns:
                - '_Perpetual'
            - UnderlyingName: INJ/USDT
              NamePatterns:
                - '_Perpetual'

      Pipeline:
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-fra-01:11800"

          V3BinaryFormat:
            DevelopmentMode: false
