QuoteServers:
  - name: qs-gateiofut-201
    image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-gateio:2025.1.21.94-914bf85
    requests:
      cpu: 1000m
      memory: 4000Mi
    limits:
      cpu: 2000m
      memory: 4000Mi
    nodeDestiny: dg-rt-az4
    tolerations:
      - key: node/destiny
        operator: Equal
        value: dg-rt-az4
        effect: NoSchedule
    prometheusPodScrape: true
    config: |-
      SecurityMaster:
       FileLoader:
         DisableNotificationsService: true
      QuoteServer:
        ShardId: 200
        ExchangeName: GateIOFut
        Monitor:
          DefaultConnectionCount: 1
          DerivedSymbols:
            Type: Futures
            Symbols:
              - UnderlyingName: BTC/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: ETH/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: APE/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: SOL/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: BNB/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: ADA/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: XRP/USDT
                NamePatterns:
                  - "_Perpetual"
              - UnderlyingName: DOGE/USDT
                NamePatterns:
                  - "_Perpetual"
        Pipeline:
          SanityCheckFilter:
            AllowEmptyL2Deltas: true
          Publisher:
            ZmqTransport:
              Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"

            V3BinaryFormat:
              DevelopmentMode: false
      PerfCollector:
        HistogramDumpInterval: 01:00:00
