apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-binancefut-216
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-binance:2024.8.27.97-d474169
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 4000Mi
  cpu_limit: 2000m
  memory_limit: 4000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    QuoteServer:
      ShardId: 215
      ExchangeName: BinanceFut

      Monitor:
        DefaultConnectionCount: 1
        DerivedSymbols:
          Type: Futures
          Symbols:
            - UnderlyingName: WOO/USDT
            - UnderlyingName: PEOPLE/USDT
            - UnderlyingName: GMT/USD
            - UnderlyingName: RUNE/USD
            - UnderlyingName: FTM/USD
            - UnderlyingName: THETA/USD
            - UnderlyingName: UNI/USD
            - UnderlyingName: TRX/USD
            - UnderlyingName: ALPHA/USDT
            - UnderlyingName: CHZ/USDT
            - UnderlyingName: GRT/USDT
            - UnderlyingName: IOST/USDT
            - UnderlyingName: RDNT/USDT
            - UnderlyingName: LOOM/USDT
            - UnderlyingName: BOND/USDT
            - UnderlyingName: ORBS/USDT
            - UnderlyingName: BIGTIME/USDT
            - UnderlyingName: WAXP/USDT
            - UnderlyingName: BSV/USDT
            - UnderlyingName: RIF/USDT
            - UnderlyingName: GAS/USDT
            - UnderlyingName: POLYX/USDT
            - UnderlyingName: POWR/USDT
            - UnderlyingName: AI/USDT
            - UnderlyingName: WIF/USDT
            - UnderlyingName: JUP/USDT
      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: 00:00:01
          PriceForChangeThreshold: 3.0e-05
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-09:11800"
          V3BinaryFormat:
            DevelopmentMode: false
