apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-huobiglobal-208
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-huobi:2024.10.29.65-57e0a79
  replicas: 1
  destiny: dg-rt-az1
  cpu_request: 1200m
  memory_request: 2000Mi
  cpu_limit: 1200m
  memory_limit: 2000Mi
  config: |
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ShardId: 207
      ExchangeName: HuobiGlobal

      Monitor:
        DefaultConnectionCount: 1
        MaxSymbolsPerConnection: 30
        Symbols:
          - Name: AVAX/USDT
          - Name: KNC/USDT
          - Name: BNT/USDT
          - Name: BAL/USDT
          - Name: UMA/USDT
          - Name: MKR/USDT
          - Name: TT/USDT
          - Name: LOKA/USDT
          - Name: WBT/USDT
          - Name: TON/USDT
          - Name: DEXE/USDT
          - Name: MAGIC/USDT
          - Name: ALI/USDT
          - Name: CVX/USDT
          - Name: RAIN/USDT
          - Name: CELO/USDT
          - Name: GMEE/USDT
          - Name: JASMY/USDT
          - Name: REVV/USDT
          - Name: DYDX/USDT
          - Name: ETH/USDC
          - Name: ICP/USDT
          - Name: SHIB/USDT
          - Name: BTC/USDC
          - Name: PHA/USDT
          - Name: ZRX/USDT
          - Name: REN/USDT
          - Name: BAND/USDT
          - Name: ROCK/USDT
          - Name: MONG/USDT
          - Name: TOX/USDT
          - Name: HUNT/USDT
          - Name: DOSE/USDT
          - Name: USDC/USDT
          - Name: USDD/USDT
          - Name: BBF/USDT
          - Name: VOXEL/USDT
          - Name: GNO/USDT
          - Name: GHST/USDT
          - Name: AUDIO/USDT
          - Name: DIA/USDT
          - Name: EGLD/USDT
          - Name: MOVR/USDT
          - Name: APE/USDT
          - Name: ACS/USDT
          - Name: IMX/USDT
          - Name: MASK/USDT
          - Name: FLOW/USDT
          - Name: API3/USDT
          - Name: HBAR/USDT
          - Name: DASH/USDT
          - Name: SSV/USDT
          - Name: DEP/USDT
          - Name: SWFTC/USDT
          - Name: FORTH/USDT
          - Name: ARPA/USDT
          - Name: XTM/USDT
          - Name: LPT/USDT
          - Name: BNB/USDT
          - Name: LIKE/USDT
      RateLimiter:
        Http:
          UsageLimit: 10
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.075
          RequestCosts:
            FundingRate: 1
      HuobiGlobal:
        Collocation: true
        UseTickFeed: false
      Pipeline:
        AbArbitrator:
          DepthBookProcessing:
            OrderBy: Counter
          TradesProcessing:
            OrderBy: Sequence
        SnapshotCoordinator:
          OrderBy: Counter
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-03:11800"
          V3BinaryFormat:
            DevelopmentMode: false
    PerfCollector:
      HistogramDumpInterval: 23:00:00
