apiVersion: tradingplatform.alphalab.cc/v1alpha1
kind: QuoteServer
metadata:
  name: qs-kucoin-211
spec:
  image: 346086605621.dkr.ecr.ap-southeast-1.amazonaws.com/alc-qs-exchange-kucoin:2024.9.10.73-b526a2d
  replicas: 1
  destiny: dg-rt-az4
  cpu_request: 2000m
  memory_request: 2000Mi
  cpu_limit: 2000m
  memory_limit: 2000Mi
  config: |
    PriceServerClient:
      Address: ">tcp://qs-tokyo.node.al:10951,>tcp://qs-tokyo-1.node.al:10951,>tcp://qs-tokyo.node.al:10956,>tcp://qs-tokyo-1.node.al:10956,>tcp://qs-tokyo-4.node.al:10951"
    SecurityMaster:
      FileLoader:
        DisableNotificationsService: true
    QuoteServer:
      ExchangeName: KuCoin
      ShardId: 210
      KuCoin:
        ApiPassphrase: UPpdoXnVJeJjAx9HzYGbmeG2hmlhJuAf
        ApiKey: 6672b0bd5ee2e4000139e38b
        ApiSecret: a87e98dd-04ff-4be1-af42-337dee963d6f
      CheckStaleMarketDataTrigger:
        Interval: 00:00:01
      Monitor:
        Symbols:
          - Name: ADS/USDT
          - Name: ZEC/BTC
          - Name: HBAR/USDT
          - Name: ZEN/USDT
          - Name: REN/USDT
          - Name: YGG/USDT
          - Name: XCH/USDT
          - Name: SWEAT/USDT
          - Name: ETH/USDT
          - Name: SDAO/USDT
          - Name: FTT/USDT
          - Name: ALICE/USDT
          - Name: XTM/USDT
          - Name: AVAX/BTC
          - Name: CFG/USDT
          - Name: BNB/BTC
          - Name: BLZ/USDT
          - Name: BONK/USDT
          - Name: SIDUS/USDT
          - Name: ETHW/USDT
          - Name: VISION/USDT
          - Name: VRA/USDT
          - Name: SUSHI/USDT
          - Name: TLOS/USDT
          - Name: VET/BTC
          - Name: USDC/USDT
          - Name: PBX/USDT
          - Name: PYR/USDT
          - Name: BLOK/USDT
          - Name: DFI/USDT
          - Name: TOKO/USDT
          - Name: LTC/BTC
          - Name: ILV/USDT
          - Name: STX/USDT
          - Name: ARPA/USDT
          - Name: ADA/USDT

      RateLimiter:
        Http:
          UsageLimit: 200
          Interval: 00:00:01
          MinAcquireGap: 0.00:00:00.10
          RequestCosts:
            Snapshot: 10
      Pipeline:
        Subsampling:
          BestBidOfferThreshold: 1e-5
          TimeThreshold: "00:00:01"
          PriceForChangeThreshold: 3.0e-5
        DepthBookMaintainer:
          LevelsCap: 150
        Publisher:
          ZmqTransport:
            Endpoint: "tcp://dg-proxy.dg-tokyo-05:11800"
          V3BinaryFormat:
            DevelopmentMode: false
        StaleMarketDataObserver:
          StaleThreshold: 00:00:01
          IdleThreshold: 00:02:00
    PerfCollector:
      HistogramDumpInterval: "23:00:00"
