apiVersion: v1
data:
  config.yaml: |
    Database:
      Port: 3306
      TableName: "funding_fee_history"
      Enabled: true

    FeePuller:
      SecretsPath: '/etc/keys'
      Exchanges:
        - Name: BinanceFut
          SpotName: Binance
          DelayBetweenApiCall: 0.00:00:1
          CronPullDefinitions:
            - "05 0 * * *"
            - "05 8 * * *"
            - "05 16 * * *"
        - Name: OKExFut
          SpotName: OKEx
          DelayBetweenApiCall: 0.00:00:1
          CronPullDefinitions:
            - "05 1 * * *"
            - "05 9 * * *"
            - "05 17 * * *"
        - Name: Bybit
          SpotName: BybitSpot
          DelayBetweenApiCall: 0.00:00:2
          CronPullDefinitions:
            - "05 0 * * *"
            - "05 8 * * *"
            - "05 16 * * *"
        - Name: GateIOFut
          SpotName: GateIO
          DelayBetweenApiCall: 0.00:00:1
          CronPullDefinitions:
            - "10 1 * * *"
            - "10 9 * * *"
            - "10 17 * * *"
        - Name: KuCoinFut
          SpotName: KuCoin
          DelayBetweenApiCall: 0.00:00:01
          CronPullDefinitions:
            - "10 1 * * *"
            - "10 9 * * *"
            - "10 17 * * *"
        # - Name: HuobiDM
        #   SpotName: HuobiGlobal
        #   DelayBetweenApiCall: 0.00:00:1
        #   CronPullDefinitions:     
        #     - "05 2 * * *"
        #     - "05 10 * * *"
        #     - "05 18 * * *"
      Accounts:
        - Exchange: BinanceFut
          SpotName: Binance
          UrlFutures: "https://fapi-binance.tyo.api-proxy.alphalab.cc/fapi/"
          UrlSpot: "https://api-binance.tyo.api-proxy.alphalab.cc"
          Names:
            - ts-binancefut-redoak
            - ts-binancefut-redoak-33
            - ts-binancefut-redoak-50
            - ts-binancefut-redoak-1001
            - ts-binancefut-redoak-1059
            - ts-binancefut-redoak-1060
            - ts-binancefut-redoak-1099
            - ts-binancefut-redoak-1100
            - ts-binancefut-redoak-1401
            - ts-binancefut-redoak-1415
            - ts-binancefut-redoak-1616
            - ts-binancefut-redoak-1635
            - ts-binancefut-redoak-1636
            - ts-binancefut-redoak-1654
            - ts-binancefut-redoak-1657
            - ts-binancefut-redoak-1658
            - ts-binancefut-redoak-1659
            - ts-binancefut-redoak-1660
            - ts-binancefut-redoak-1661
            - ts-binancefut-redoak-1662
            - ts-binancefut-redoak-1663
            - ts-binancefut-redoak-1664
            - ts-binancefut-redoak-1666
            - ts-binancefut-redoak-1670
            - ts-binancefut-redoak-1672
            - ts-binancefut-redoak-1679
            - ts-binancefut-redoak-1701
            - ts-binancefut-redoak-1702
            - ts-binancefut-redoak-1703
            - ts-binancefut-redoak-1704
            - ts-binancefut-redoak-1705
            - ts-binancefut-redoak-1710
            - ts-binancefut-redoak-1750
            - ts-binancefut-redoak-1748
            - ts-binancefut-redoak-1751
            - ts-binancefut-redoak-1752
            - ts-binancefut-redoak-1753
            - ts-binancefut-redoak-1754
            - ts-binancefut-redoak-1680
            - ts-binancefut-redoak-1681
            - ts-binancefut-redoak-1756
            - ts-binancefut-redoak-1626
        - Exchange: BinanceFut
          SpotName: Binance
          UrlFutures: "https://dapi-binance.tyo.api-proxy.alphalab.cc/dapi/"
          UrlSpot: "https://api-binance.tyo.api-proxy.alphalab.cc"
          Names:
            - ts-binancefut-coin-redoak-1060
            - ts-binancefut-coin-redoak-1748
            - ts-binancefut-coin-redoak-1751
            - ts-binancefut-coin-redoak-1752
            - ts-binancefut-coin-redoak-1754
            - ts-binancefut-coin-redoak-1753
        # - Exchange: HuobiDM
        #   SpotName: HuobiGlobal
        #   UrlFutures: "https://api-hbdm.tyo.api-proxy.alphalab.cc"
        #   UrlSpot: "https://api-huobi-pro.tyo.api-proxy.alphalab.cc"
        #   Names:
        #     - ts-huobidm-usdt-perpetuals-redoak-5
        - Exchange: OKExFut
          UrlFutures: "https://okx.hkg-2.api-proxy.alphalab.cc"
          UrlSpot: "https://okx.hkg-2.api-proxy.alphalab.cc"
          Names:
            - ts-okexfut-perpetuals-redoak-1
            - ts-okexfut-perpetuals-redoak-3
            - ts-okexfut-perpetuals-redoak-4
            - ts-okexfut-perpetuals-redoak-5
            - ts-okexfut-perpetuals-redoak-13
            - ts-okexfut-perpetuals-redoak-14
            - ts-okexfut-perpetuals-redoak-15
            - ts-okexfut-perpetuals-redoak-16
            - ts-okexfut-perpetuals-redoak-17
        - Exchange: Bybit
          UrlFutures: "https://api-bybit-com-is-13-228-127-121.sin.api-proxy.alphalab.cc"
          UrlSpot: "https://api-bybit-com-is-13-228-127-121.sin.api-proxy.alphalab.cc"
          Names:
            - ts-bybit-unified-redoak-22
            - ts-bybit-unified-redoak-23
            - ts-bybit-unified-redoak-24
            - ts-bybit-unified-redoak-25
            - ts-bybit-unified-redoak-26
            - ts-bybit-unified-redoak-27
            - ts-bybit-unified-redoak-28
            - ts-bybit-unified-redoak-29
            - ts-bybit-unified-redoak-30
            - ts-bybit-unified-redoak-41
            - ts-bybit-usdt-perpetuals-redoak-42
            - ts-bybit-usdt-perpetuals-redoak-9
        - Exchange: GateIOFut
          UrlFutures: https://gateio-is-3-39-15-206.sel.api-proxy.alphalab.cc
          UrlSpot: https://gateio-is-3-39-15-206.sel.api-proxy.alphalab.cc
          Names:
            - ts-gateiofut-redoak-32
            - ts-gateiofut-redoak-33
            - ts-gateiofut-redoak-34
            - ts-gateiofut-redoak-35
            - ts-gateiofut-redoak-36
            - ts-gateiofut-redoak-37
            - ts-gateiofut-redoak-38
            - ts-gateiofut-redoak-39
            - ts-gateiofut-redoak-40
        - Exchange: KuCoinFut
          UrlFutures: "https://kucoin-futures-is-13-228-127-121.sin.api-proxy.alphalab.cc"
          UrlSpot: "https://kucoin-is-13-228-127-121.sin.api-proxy.alphalab.cc"
          Names:
            - ts-kucoinfut-redoak-41
            - ts-kucoinfut-redoak-42
            - ts-kucoinfut-redoak-43
            - ts-kucoinfut-redoak-44
            - ts-kucoinfut-redoak-45
            - ts-kucoinfut-redoak-46
            - ts-kucoinfut-redoak-47
            - ts-kucoinfut-redoak-48
            - ts-kucoinfut-redoak-49
      FundingRate:
        RequestAddress: ">tcp://alc-funding-rate-broadcaster.dg-sin-01.svc.cluster.local:10002"
        RequestTopic: "requestFundingRate"
        ResponseAddress: ">tcp://alc-funding-rate-broadcaster.dg-sin-01.svc.cluster.local:10001"
        ResponseTopic: "responseFundingRate"
      BlacklistedSymbols:
        - "huobidm_mir_usdt_perpetual"
        - "okexfut_lon_usdt_perpetual"
        - "okexfut_wncg_usdt_perpetual"
        - "okexfut_btt_usdt_perpetual"
        - "okexfut_srm_usdt_perpetual"
        - "okexfut_sos_usdt_perpetual"
        - "okexfut_sc_usdt_perpetual"
    
kind: ConfigMap
metadata:
  name: alc-funding-fee-puller-config
  namespace: funding-fee-puller
